#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'turtlebot3-dqn','console_scripts','dqn_gazebo'
__requires__ = 'turtlebot3-dqn'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('turtlebot3-dqn', 'console_scripts', 'dqn_gazebo')()
    )
