// Generated by gencpp from file dynamic_tf_publisher/SetDynamicTF.msg
// DO NOT EDIT!


#ifndef DYNAMIC_TF_PUBLISHER_MESSAGE_SETDYNAMICTF_H
#define DYNAMIC_TF_PUBLISHER_MESSAGE_SETDYNAMICTF_H

#include <ros/service_traits.h>


#include <dynamic_tf_publisher/SetDynamicTFRequest.h>
#include <dynamic_tf_publisher/SetDynamicTFResponse.h>


namespace dynamic_tf_publisher
{

struct SetDynamicTF
{

typedef SetDynamicTFRequest Request;
typedef SetDynamicTFResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetDynamicTF
} // namespace dynamic_tf_publisher


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dynamic_tf_publisher::SetDynamicTF > {
  static const char* value()
  {
    return "257be6eb2c49e846d6c3c12c85bb0fb1";
  }

  static const char* value(const ::dynamic_tf_publisher::SetDynamicTF&) { return value(); }
};

template<>
struct DataType< ::dynamic_tf_publisher::SetDynamicTF > {
  static const char* value()
  {
    return "dynamic_tf_publisher/SetDynamicTF";
  }

  static const char* value(const ::dynamic_tf_publisher::SetDynamicTF&) { return value(); }
};


// service_traits::MD5Sum< ::dynamic_tf_publisher::SetDynamicTFRequest> should match 
// service_traits::MD5Sum< ::dynamic_tf_publisher::SetDynamicTF > 
template<>
struct MD5Sum< ::dynamic_tf_publisher::SetDynamicTFRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dynamic_tf_publisher::SetDynamicTF >::value();
  }
  static const char* value(const ::dynamic_tf_publisher::SetDynamicTFRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamic_tf_publisher::SetDynamicTFRequest> should match 
// service_traits::DataType< ::dynamic_tf_publisher::SetDynamicTF > 
template<>
struct DataType< ::dynamic_tf_publisher::SetDynamicTFRequest>
{
  static const char* value()
  {
    return DataType< ::dynamic_tf_publisher::SetDynamicTF >::value();
  }
  static const char* value(const ::dynamic_tf_publisher::SetDynamicTFRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dynamic_tf_publisher::SetDynamicTFResponse> should match 
// service_traits::MD5Sum< ::dynamic_tf_publisher::SetDynamicTF > 
template<>
struct MD5Sum< ::dynamic_tf_publisher::SetDynamicTFResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dynamic_tf_publisher::SetDynamicTF >::value();
  }
  static const char* value(const ::dynamic_tf_publisher::SetDynamicTFResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamic_tf_publisher::SetDynamicTFResponse> should match 
// service_traits::DataType< ::dynamic_tf_publisher::SetDynamicTF > 
template<>
struct DataType< ::dynamic_tf_publisher::SetDynamicTFResponse>
{
  static const char* value()
  {
    return DataType< ::dynamic_tf_publisher::SetDynamicTF >::value();
  }
  static const char* value(const ::dynamic_tf_publisher::SetDynamicTFResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DYNAMIC_TF_PUBLISHER_MESSAGE_SETDYNAMICTF_H
