
classdef ErrorCodes < ros.Message
    %ErrorCodes MATLAB implementation of iai_kinematics_msgs/ErrorCodes
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'iai_kinematics_msgs/ErrorCodes' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '5acf26755415e1ec18a6d523028f204d' % The MD5 Checksum of the message definition
        PropertyList = { 'Val' } % List of non-constant message properties
        ROSPropertyList = { 'val' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
        PLANNINGFAILED = int32(-1)
        SUCCESS = int32(1)
        TIMEDOUT = int32(-2)
        STARTSTATEINCOLLISION = int32(-3)
        STARTSTATEVIOLATESPATHCONSTRAINTS = int32(-4)
        GOALINCOLLISION = int32(-5)
        GOALVIOLATESPATHCONSTRAINTS = int32(-6)
        INVALIDROBOTSTATE = int32(-7)
        INCOMPLETEROBOTSTATE = int32(-8)
        INVALIDPLANNERID = int32(-9)
        INVALIDNUMPLANNINGATTEMPTS = int32(-10)
        INVALIDALLOWEDPLANNINGTIME = int32(-11)
        INVALIDGROUPNAME = int32(-12)
        INVALIDGOALJOINTCONSTRAINTS = int32(-13)
        INVALIDGOALPOSITIONCONSTRAINTS = int32(-14)
        INVALIDGOALORIENTATIONCONSTRAINTS = int32(-15)
        INVALIDPATHJOINTCONSTRAINTS = int32(-16)
        INVALIDPATHPOSITIONCONSTRAINTS = int32(-17)
        INVALIDPATHORIENTATIONCONSTRAINTS = int32(-18)
        INVALIDTRAJECTORY = int32(-19)
        INVALIDINDEX = int32(-20)
        JOINTLIMITSVIOLATED = int32(-21)
        PATHCONSTRAINTSVIOLATED = int32(-22)
        COLLISIONCONSTRAINTSVIOLATED = int32(-23)
        GOALCONSTRAINTSVIOLATED = int32(-24)
        JOINTSNOTMOVING = int32(-25)
        TRAJECTORYCONTROLLERFAILED = int32(-26)
        FRAMETRANSFORMFAILURE = int32(-27)
        COLLISIONCHECKINGUNAVAILABLE = int32(-28)
        ROBOTSTATESTALE = int32(-29)
        SENSORINFOSTALE = int32(-30)
        NOIKSOLUTION = int32(-31)
        INVALIDLINKNAME = int32(-32)
        IKLINKINCOLLISION = int32(-33)
        NOFKSOLUTION = int32(-34)
        KINEMATICSSTATEINCOLLISION = int32(-35)
        INVALIDTIMEOUT = int32(-36)
    end
    properties
        Val
    end
    methods
        function set.Val(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ErrorCodes', 'Val');
            obj.Val = int32(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.iai_kinematics_msgs.ErrorCodes.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.iai_kinematics_msgs.ErrorCodes(strObj);
        end
    end
end
