// Generated by gencpp from file hrpsys_gazebo_msgs/RobotState.msg
// DO NOT EDIT!


#ifndef HRPSYS_GAZEBO_MSGS_MESSAGE_ROBOTSTATE_H
#define HRPSYS_GAZEBO_MSGS_MESSAGE_ROBOTSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <hrpsys_gazebo_msgs/NamedImu.h>
#include <hrpsys_gazebo_msgs/NamedWrench.h>

namespace hrpsys_gazebo_msgs
{
template <class ContainerAllocator>
struct RobotState_
{
  typedef RobotState_<ContainerAllocator> Type;

  RobotState_()
    : header()
    , position()
    , velocity()
    , effort()
    , ref_position()
    , ref_velocity()
    , kp_position()
    , ki_position()
    , kd_position()
    , kp_velocity()
    , i_effort_min()
    , i_effort_max()
    , kpv_position()
    , kpv_velocity()
    , Imus()
    , sensors()  {
    }
  RobotState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , position(_alloc)
    , velocity(_alloc)
    , effort(_alloc)
    , ref_position(_alloc)
    , ref_velocity(_alloc)
    , kp_position(_alloc)
    , ki_position(_alloc)
    , kd_position(_alloc)
    , kp_velocity(_alloc)
    , i_effort_min(_alloc)
    , i_effort_max(_alloc)
    , kpv_position(_alloc)
    , kpv_velocity(_alloc)
    , Imus(_alloc)
    , sensors(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _position_type;
  _position_type position;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _velocity_type;
  _velocity_type velocity;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _effort_type;
  _effort_type effort;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _ref_position_type;
  _ref_position_type ref_position;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _ref_velocity_type;
  _ref_velocity_type ref_velocity;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _kp_position_type;
  _kp_position_type kp_position;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _ki_position_type;
  _ki_position_type ki_position;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _kd_position_type;
  _kd_position_type kd_position;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _kp_velocity_type;
  _kp_velocity_type kp_velocity;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _i_effort_min_type;
  _i_effort_min_type i_effort_min;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _i_effort_max_type;
  _i_effort_max_type i_effort_max;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _kpv_position_type;
  _kpv_position_type kpv_position;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _kpv_velocity_type;
  _kpv_velocity_type kpv_velocity;

   typedef std::vector< ::hrpsys_gazebo_msgs::NamedImu_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::hrpsys_gazebo_msgs::NamedImu_<ContainerAllocator> >::other >  _Imus_type;
  _Imus_type Imus;

   typedef std::vector< ::hrpsys_gazebo_msgs::NamedWrench_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::hrpsys_gazebo_msgs::NamedWrench_<ContainerAllocator> >::other >  _sensors_type;
  _sensors_type sensors;





  typedef boost::shared_ptr< ::hrpsys_gazebo_msgs::RobotState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hrpsys_gazebo_msgs::RobotState_<ContainerAllocator> const> ConstPtr;

}; // struct RobotState_

typedef ::hrpsys_gazebo_msgs::RobotState_<std::allocator<void> > RobotState;

typedef boost::shared_ptr< ::hrpsys_gazebo_msgs::RobotState > RobotStatePtr;
typedef boost::shared_ptr< ::hrpsys_gazebo_msgs::RobotState const> RobotStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hrpsys_gazebo_msgs::RobotState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hrpsys_gazebo_msgs::RobotState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hrpsys_gazebo_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/mathworks/home/pmurali/Documents/Working/matlab_msg_gen_ros1/glnxa64/src/geometry_msgs/msg'], 'std_msgs': ['/mathworks/devel/sbs/31/pmurali.Brobot.j1329247.2/matlab/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg', '/mathworks/devel/sbs/31/pmurali.Brobot.j1329247.2/matlab/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg'], 'hrpsys_gazebo_msgs': ['/mathworks/home/pmurali/Documents/Working/matlab_msg_gen_ros1/glnxa64/src/hrpsys_gazebo_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hrpsys_gazebo_msgs::RobotState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hrpsys_gazebo_msgs::RobotState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hrpsys_gazebo_msgs::RobotState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hrpsys_gazebo_msgs::RobotState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hrpsys_gazebo_msgs::RobotState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hrpsys_gazebo_msgs::RobotState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hrpsys_gazebo_msgs::RobotState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0e5119eeb4843d3845bd61c692d5c24e";
  }

  static const char* value(const ::hrpsys_gazebo_msgs::RobotState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0e5119eeb4843d38ULL;
  static const uint64_t static_value2 = 0x45bd61c692d5c24eULL;
};

template<class ContainerAllocator>
struct DataType< ::hrpsys_gazebo_msgs::RobotState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hrpsys_gazebo_msgs/RobotState";
  }

  static const char* value(const ::hrpsys_gazebo_msgs::RobotState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hrpsys_gazebo_msgs::RobotState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"float64[] position\n"
"float64[] velocity\n"
"float64[] effort\n"
"\n"
"float64[] ref_position\n"
"float64[] ref_velocity\n"
"\n"
"float32[] kp_position\n"
"float32[] ki_position\n"
"float32[] kd_position\n"
"float32[] kp_velocity\n"
"\n"
"float32[] i_effort_min\n"
"float32[] i_effort_max\n"
"\n"
"float32[] kpv_position\n"
"float32[] kpv_velocity\n"
"\n"
"NamedImu[] Imus\n"
"\n"
"NamedWrench[] sensors\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: hrpsys_gazebo_msgs/NamedImu\n"
"string name\n"
"string frame_id\n"
"geometry_msgs/Quaternion orientation\n"
"geometry_msgs/Vector3 angular_velocity\n"
"geometry_msgs/Vector3 linear_acceleration\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: hrpsys_gazebo_msgs/NamedWrench\n"
"string name\n"
"string frame_id\n"
"geometry_msgs/Vector3  force\n"
"geometry_msgs/Vector3  torque\n"
;
  }

  static const char* value(const ::hrpsys_gazebo_msgs::RobotState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hrpsys_gazebo_msgs::RobotState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.position);
      stream.next(m.velocity);
      stream.next(m.effort);
      stream.next(m.ref_position);
      stream.next(m.ref_velocity);
      stream.next(m.kp_position);
      stream.next(m.ki_position);
      stream.next(m.kd_position);
      stream.next(m.kp_velocity);
      stream.next(m.i_effort_min);
      stream.next(m.i_effort_max);
      stream.next(m.kpv_position);
      stream.next(m.kpv_velocity);
      stream.next(m.Imus);
      stream.next(m.sensors);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hrpsys_gazebo_msgs::RobotState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hrpsys_gazebo_msgs::RobotState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.position[i]);
    }
    s << indent << "velocity[]" << std::endl;
    for (size_t i = 0; i < v.velocity.size(); ++i)
    {
      s << indent << "  velocity[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.velocity[i]);
    }
    s << indent << "effort[]" << std::endl;
    for (size_t i = 0; i < v.effort.size(); ++i)
    {
      s << indent << "  effort[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.effort[i]);
    }
    s << indent << "ref_position[]" << std::endl;
    for (size_t i = 0; i < v.ref_position.size(); ++i)
    {
      s << indent << "  ref_position[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.ref_position[i]);
    }
    s << indent << "ref_velocity[]" << std::endl;
    for (size_t i = 0; i < v.ref_velocity.size(); ++i)
    {
      s << indent << "  ref_velocity[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.ref_velocity[i]);
    }
    s << indent << "kp_position[]" << std::endl;
    for (size_t i = 0; i < v.kp_position.size(); ++i)
    {
      s << indent << "  kp_position[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.kp_position[i]);
    }
    s << indent << "ki_position[]" << std::endl;
    for (size_t i = 0; i < v.ki_position.size(); ++i)
    {
      s << indent << "  ki_position[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.ki_position[i]);
    }
    s << indent << "kd_position[]" << std::endl;
    for (size_t i = 0; i < v.kd_position.size(); ++i)
    {
      s << indent << "  kd_position[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.kd_position[i]);
    }
    s << indent << "kp_velocity[]" << std::endl;
    for (size_t i = 0; i < v.kp_velocity.size(); ++i)
    {
      s << indent << "  kp_velocity[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.kp_velocity[i]);
    }
    s << indent << "i_effort_min[]" << std::endl;
    for (size_t i = 0; i < v.i_effort_min.size(); ++i)
    {
      s << indent << "  i_effort_min[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.i_effort_min[i]);
    }
    s << indent << "i_effort_max[]" << std::endl;
    for (size_t i = 0; i < v.i_effort_max.size(); ++i)
    {
      s << indent << "  i_effort_max[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.i_effort_max[i]);
    }
    s << indent << "kpv_position[]" << std::endl;
    for (size_t i = 0; i < v.kpv_position.size(); ++i)
    {
      s << indent << "  kpv_position[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.kpv_position[i]);
    }
    s << indent << "kpv_velocity[]" << std::endl;
    for (size_t i = 0; i < v.kpv_velocity.size(); ++i)
    {
      s << indent << "  kpv_velocity[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.kpv_velocity[i]);
    }
    s << indent << "Imus[]" << std::endl;
    for (size_t i = 0; i < v.Imus.size(); ++i)
    {
      s << indent << "  Imus[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::hrpsys_gazebo_msgs::NamedImu_<ContainerAllocator> >::stream(s, indent + "    ", v.Imus[i]);
    }
    s << indent << "sensors[]" << std::endl;
    for (size_t i = 0; i < v.sensors.size(); ++i)
    {
      s << indent << "  sensors[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::hrpsys_gazebo_msgs::NamedWrench_<ContainerAllocator> >::stream(s, indent + "    ", v.sensors[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HRPSYS_GAZEBO_MSGS_MESSAGE_ROBOTSTATE_H
