
classdef Pose < ros.Message
    %Pose MATLAB implementation of turtlesim/Pose
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'turtlesim/Pose' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '863b248d5016ca62ea2e895ae5265cf9' % The MD5 Checksum of the message definition
        PropertyList = { 'X' 'Y' 'Theta' 'LinearVelocity' 'AngularVelocity' } % List of non-constant message properties
        ROSPropertyList = { 'x' 'y' 'theta' 'linear_velocity' 'angular_velocity' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        X
        Y
        Theta
        LinearVelocity
        AngularVelocity
    end
    methods
        function set.X(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Pose', 'X');
            obj.X = single(val);
        end
        function set.Y(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Pose', 'Y');
            obj.Y = single(val);
        end
        function set.Theta(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Pose', 'Theta');
            obj.Theta = single(val);
        end
        function set.LinearVelocity(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Pose', 'LinearVelocity');
            obj.LinearVelocity = single(val);
        end
        function set.AngularVelocity(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Pose', 'AngularVelocity');
            obj.AngularVelocity = single(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.turtlesim.Pose.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.turtlesim.Pose(strObj);
        end
    end
end
