function msgClass = getMsgClass(messageType)
%This function is for internal use only. It may be removed in the future.

%GETMSGCLASS returns a message class name of a given message type.

%   Copyright 2021 The MathWorks, Inc.

% For handling the user-facing class of non-generated message classes
specialMsgClassMap = ...
    containers.Map({'ros/Duration', ...
    'ros/Time', ...
    'geometry_msgs/Quaternion', ...
    'geometry_msgs/TransformStamped', ...
    'nav_msgs/OccupancyGrid', ...
    'octomap_msgs/Octomap', ...
    'sensor_msgs/CompressedImage', ...
    'sensor_msgs/Image', ...
    'sensor_msgs/LaserScan', ...
    'sensor_msgs/PointCloud2'}, ...
    {'ros.msg.Duration', ...
    'ros.msg.Time', ...
    'ros.msg.geometry_msgs.Quaternion', ...
    'ros.msg.geometry_msgs.TransformStamped', ...
    'ros.msg.nav_msgs.OccupancyGrid', ...
    'ros.msg.octomap_msgs.Octomap', ...
    'ros.msg.sensor_msgs.CompressedImage', ...
    'ros.msg.sensor_msgs.Image', ...
    'ros.msg.sensor_msgs.LaserScan', ...
    'ros.msg.sensor_msgs.PointCloud2'});

[pkgName, msgName] = fileparts(messageType);
if isKey(specialMsgClassMap,messageType)
    msgClass = specialMsgClassMap(messageType);
else
    msgClass = ['ros.msggen.' pkgName '.' msgName];
end
end
