// Generated by gencpp from file capabilities/EstablishBondResponse.msg
// DO NOT EDIT!


#ifndef CAPABILITIES_MESSAGE_ESTABLISHBONDRESPONSE_H
#define CAPABILITIES_MESSAGE_ESTABLISHBONDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace capabilities
{
template <class ContainerAllocator>
struct EstablishBondResponse_
{
  typedef EstablishBondResponse_<ContainerAllocator> Type;

  EstablishBondResponse_()
    : bond_id()  {
    }
  EstablishBondResponse_(const ContainerAllocator& _alloc)
    : bond_id(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _bond_id_type;
  _bond_id_type bond_id;





  typedef boost::shared_ptr< ::capabilities::EstablishBondResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::capabilities::EstablishBondResponse_<ContainerAllocator> const> ConstPtr;

}; // struct EstablishBondResponse_

typedef ::capabilities::EstablishBondResponse_<std::allocator<void> > EstablishBondResponse;

typedef boost::shared_ptr< ::capabilities::EstablishBondResponse > EstablishBondResponsePtr;
typedef boost::shared_ptr< ::capabilities::EstablishBondResponse const> EstablishBondResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::capabilities::EstablishBondResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::capabilities::EstablishBondResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::capabilities::EstablishBondResponse_<ContainerAllocator1> & lhs, const ::capabilities::EstablishBondResponse_<ContainerAllocator2> & rhs)
{
  return lhs.bond_id == rhs.bond_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::capabilities::EstablishBondResponse_<ContainerAllocator1> & lhs, const ::capabilities::EstablishBondResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace capabilities

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::capabilities::EstablishBondResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::capabilities::EstablishBondResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::capabilities::EstablishBondResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::capabilities::EstablishBondResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::capabilities::EstablishBondResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::capabilities::EstablishBondResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::capabilities::EstablishBondResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5dec67991af973eddfa86dc20c3faef0";
  }

  static const char* value(const ::capabilities::EstablishBondResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5dec67991af973edULL;
  static const uint64_t static_value2 = 0xdfa86dc20c3faef0ULL;
};

template<class ContainerAllocator>
struct DataType< ::capabilities::EstablishBondResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "capabilities/EstablishBondResponse";
  }

  static const char* value(const ::capabilities::EstablishBondResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::capabilities::EstablishBondResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string bond_id\n"
"\n"
;
  }

  static const char* value(const ::capabilities::EstablishBondResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::capabilities::EstablishBondResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bond_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EstablishBondResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::capabilities::EstablishBondResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::capabilities::EstablishBondResponse_<ContainerAllocator>& v)
  {
    s << indent << "bond_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.bond_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAPABILITIES_MESSAGE_ESTABLISHBONDRESPONSE_H
