// Generated by gencpp from file r2_msgs/ResetTableScene.msg
// DO NOT EDIT!


#ifndef R2_MSGS_MESSAGE_RESETTABLESCENE_H
#define R2_MSGS_MESSAGE_RESETTABLESCENE_H

#include <ros/service_traits.h>


#include <r2_msgs/ResetTableSceneRequest.h>
#include <r2_msgs/ResetTableSceneResponse.h>


namespace r2_msgs
{

struct ResetTableScene
{

typedef ResetTableSceneRequest Request;
typedef ResetTableSceneResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetTableScene
} // namespace r2_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::r2_msgs::ResetTableScene > {
  static const char* value()
  {
    return "c95f6c9db0edf7da4840d218c33352c7";
  }

  static const char* value(const ::r2_msgs::ResetTableScene&) { return value(); }
};

template<>
struct DataType< ::r2_msgs::ResetTableScene > {
  static const char* value()
  {
    return "r2_msgs/ResetTableScene";
  }

  static const char* value(const ::r2_msgs::ResetTableScene&) { return value(); }
};


// service_traits::MD5Sum< ::r2_msgs::ResetTableSceneRequest> should match 
// service_traits::MD5Sum< ::r2_msgs::ResetTableScene > 
template<>
struct MD5Sum< ::r2_msgs::ResetTableSceneRequest>
{
  static const char* value()
  {
    return MD5Sum< ::r2_msgs::ResetTableScene >::value();
  }
  static const char* value(const ::r2_msgs::ResetTableSceneRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::r2_msgs::ResetTableSceneRequest> should match 
// service_traits::DataType< ::r2_msgs::ResetTableScene > 
template<>
struct DataType< ::r2_msgs::ResetTableSceneRequest>
{
  static const char* value()
  {
    return DataType< ::r2_msgs::ResetTableScene >::value();
  }
  static const char* value(const ::r2_msgs::ResetTableSceneRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::r2_msgs::ResetTableSceneResponse> should match 
// service_traits::MD5Sum< ::r2_msgs::ResetTableScene > 
template<>
struct MD5Sum< ::r2_msgs::ResetTableSceneResponse>
{
  static const char* value()
  {
    return MD5Sum< ::r2_msgs::ResetTableScene >::value();
  }
  static const char* value(const ::r2_msgs::ResetTableSceneResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::r2_msgs::ResetTableSceneResponse> should match 
// service_traits::DataType< ::r2_msgs::ResetTableScene > 
template<>
struct DataType< ::r2_msgs::ResetTableSceneResponse>
{
  static const char* value()
  {
    return DataType< ::r2_msgs::ResetTableScene >::value();
  }
  static const char* value(const ::r2_msgs::ResetTableSceneResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // R2_MSGS_MESSAGE_RESETTABLESCENE_H
