// Generated by gencpp from file pr2_gripper_sensor_msgs/PR2GripperEventDetectorAction.msg
// DO NOT EDIT!


#ifndef PR2_GRIPPER_SENSOR_MSGS_MESSAGE_PR2GRIPPEREVENTDETECTORACTION_H
#define PR2_GRIPPER_SENSOR_MSGS_MESSAGE_PR2GRIPPEREVENTDETECTORACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <pr2_gripper_sensor_msgs/PR2GripperEventDetectorActionGoal.h>
#include <pr2_gripper_sensor_msgs/PR2GripperEventDetectorActionResult.h>
#include <pr2_gripper_sensor_msgs/PR2GripperEventDetectorActionFeedback.h>

namespace pr2_gripper_sensor_msgs
{
template <class ContainerAllocator>
struct PR2GripperEventDetectorAction_
{
  typedef PR2GripperEventDetectorAction_<ContainerAllocator> Type;

  PR2GripperEventDetectorAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  PR2GripperEventDetectorAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::pr2_gripper_sensor_msgs::PR2GripperEventDetectorActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::pr2_gripper_sensor_msgs::PR2GripperEventDetectorActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::pr2_gripper_sensor_msgs::PR2GripperEventDetectorActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::pr2_gripper_sensor_msgs::PR2GripperEventDetectorAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pr2_gripper_sensor_msgs::PR2GripperEventDetectorAction_<ContainerAllocator> const> ConstPtr;

}; // struct PR2GripperEventDetectorAction_

typedef ::pr2_gripper_sensor_msgs::PR2GripperEventDetectorAction_<std::allocator<void> > PR2GripperEventDetectorAction;

typedef boost::shared_ptr< ::pr2_gripper_sensor_msgs::PR2GripperEventDetectorAction > PR2GripperEventDetectorActionPtr;
typedef boost::shared_ptr< ::pr2_gripper_sensor_msgs::PR2GripperEventDetectorAction const> PR2GripperEventDetectorActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pr2_gripper_sensor_msgs::PR2GripperEventDetectorAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pr2_gripper_sensor_msgs::PR2GripperEventDetectorAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pr2_gripper_sensor_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'pr2_gripper_sensor_msgs': ['/local-ssd1/All_Custom_Msgs/PendingActionPackagesPart2/matlab_msg_gen_ros1/glnxa64/src/pr2_gripper_sensor_msgs/msg', '/local-ssd1/All_Custom_Msgs/PendingActionPackagesPart2/matlab_msg_gen_ros1/glnxa64/devel/share/pr2_gripper_sensor_msgs/msg'], 'actionlib': ['/mathworks/devel/sbs/31/hakakarl.Brobot.j1347395/matlab/sys/ros1/glnxa64/ros1/share/actionlib/cmake/../msg'], 'std_msgs': ['/mathworks/devel/sbs/31/hakakarl.Brobot.j1347395/matlab/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/mathworks/devel/sbs/31/hakakarl.Brobot.j1347395/matlab/sys/ros1/glnxa64/ros1/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pr2_gripper_sensor_msgs::PR2GripperEventDetectorAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pr2_gripper_sensor_msgs::PR2GripperEventDetectorAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr2_gripper_sensor_msgs::PR2GripperEventDetectorAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr2_gripper_sensor_msgs::PR2GripperEventDetectorAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr2_gripper_sensor_msgs::PR2GripperEventDetectorAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr2_gripper_sensor_msgs::PR2GripperEventDetectorAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pr2_gripper_sensor_msgs::PR2GripperEventDetectorAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d4e2ee2d04e941280f34bdb366daa9a4";
  }

  static const char* value(const ::pr2_gripper_sensor_msgs::PR2GripperEventDetectorAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd4e2ee2d04e94128ULL;
  static const uint64_t static_value2 = 0x0f34bdb366daa9a4ULL;
};

template<class ContainerAllocator>
struct DataType< ::pr2_gripper_sensor_msgs::PR2GripperEventDetectorAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pr2_gripper_sensor_msgs/PR2GripperEventDetectorAction";
  }

  static const char* value(const ::pr2_gripper_sensor_msgs::PR2GripperEventDetectorAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pr2_gripper_sensor_msgs::PR2GripperEventDetectorAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"PR2GripperEventDetectorActionGoal action_goal\n"
"PR2GripperEventDetectorActionResult action_result\n"
"PR2GripperEventDetectorActionFeedback action_feedback\n"
"\n"
"================================================================================\n"
"MSG: pr2_gripper_sensor_msgs/PR2GripperEventDetectorActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"PR2GripperEventDetectorGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: pr2_gripper_sensor_msgs/PR2GripperEventDetectorGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Event Detector action used to tell detect events happening on the \n"
"# palm mounted accelerometer and finger pressure sensors\n"
"\n"
"#goal\n"
"PR2GripperEventDetectorCommand command\n"
"\n"
"================================================================================\n"
"MSG: pr2_gripper_sensor_msgs/PR2GripperEventDetectorCommand\n"
"# state variable that defines what events we would like to trigger on\n"
"# Leaving this field blank will result in the robot triggering when \n"
"# anything touches the sides of the finger or an impact is detected\n"
"# with the hand/arm.\n"
"int8 trigger_conditions\n"
"# definitions for our various trigger_conditions values\n"
"# trigger on either acceleration contact or finger sensor side impact\n"
"int8 FINGER_SIDE_IMPACT_OR_ACC = 0\n"
"# tigger once  both slip and acceleration signals occur\n"
"int8 SLIP_AND_ACC = 1 \n"
"#  trigger on either slip, acceleration, or finger sensor side impact\n"
"int8 FINGER_SIDE_IMPACT_OR_SLIP_OR_ACC = 2\n"
"# trigger only on slip information\n"
"int8 SLIP = 3\n"
"# trigger only on acceleration contact information\n"
"int8 ACC = 4 \n"
"\n"
"\n"
"# the amount of acceleration to trigger on (acceleration vector magnitude)\n"
"# Units = m/s^2\n"
"# The user needs to be concerned here about not setting the trigger too\n"
"# low so that is set off by the robot's own motions.\n"
"#\n"
"# For large rapid motions, say by a motion planner, 5 m/s^2 is a good level\n"
"# For small delicate controlled motions this can be set MUCH lower (try 2.0)\n"
"#\n"
"# NOTE: When moving the gripper joint (opening/closing the grippr)\n"
"# the high gearing of the PR2 gripper causes large acceleration vibrations\n"
"# which will cause triggering to occur. This is a known drawback of the PR2.\n"
"#\n"
"# NOTE: Leaving this value blank will result in a 0 m/s^2 trigger. If you\n"
"# are using a trigger_conditions value that returns on acceleration contact\n"
"# events then it will immediately exceed your trigger and return\n"
"float64 acceleration_trigger_magnitude\n"
"\n"
"\n"
"# the slip detector gain to trigger on (either finger) : try 0.01\n"
"# higher values decrease slip sensitivty (to a point)\n"
"# lower values increase sensitivity (to a point)\n"
"#\n"
"# NOTE: Leaving this value blank will result in the most sensitive slip level.\n"
"float64 slip_trigger_magnitude\n"
"================================================================================\n"
"MSG: pr2_gripper_sensor_msgs/PR2GripperEventDetectorActionResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"PR2GripperEventDetectorResult result\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: pr2_gripper_sensor_msgs/PR2GripperEventDetectorResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#results\n"
"PR2GripperEventDetectorData data\n"
"\n"
"================================================================================\n"
"MSG: pr2_gripper_sensor_msgs/PR2GripperEventDetectorData\n"
"# Time the data was recorded at\n"
"time stamp\n"
"\n"
"# true if the trigger conditions have been met \n"
"# (see PR2GripperEventDetectorCommand)\n"
"bool trigger_conditions_met\n"
"\n"
"# true if the pressure sensors detected a slip event\n"
"# slip events occur when the finger pressure sensors\n"
"# high-freq. content exceeds the slip_trigger_magnitude variable\n"
"# (see PR2GripperEventDetectorCommand)\n"
"bool slip_event\n"
"\n"
"# true if the hand-mounted accelerometer detected a contact acceleration\n"
"# acceleration events occur when the palm accelerometer\n"
"# high-freq. content exceeds the acc_trigger_magnitude variable\n"
"# (see PR2GripperEventDetectorCommand)\n"
"bool acceleration_event\n"
"\n"
"# the high-freq acceleration vector that was last seen (x,y,z)\n"
"float64[3] acceleration_vector\n"
"================================================================================\n"
"MSG: pr2_gripper_sensor_msgs/PR2GripperEventDetectorActionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"PR2GripperEventDetectorFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: pr2_gripper_sensor_msgs/PR2GripperEventDetectorFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# feedback\n"
"PR2GripperEventDetectorData data\n"
"\n"
"\n"
;
  }

  static const char* value(const ::pr2_gripper_sensor_msgs::PR2GripperEventDetectorAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pr2_gripper_sensor_msgs::PR2GripperEventDetectorAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PR2GripperEventDetectorAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pr2_gripper_sensor_msgs::PR2GripperEventDetectorAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pr2_gripper_sensor_msgs::PR2GripperEventDetectorAction_<ContainerAllocator>& v)
  {
    s << indent << "action_goal: ";
    s << std::endl;
    Printer< ::pr2_gripper_sensor_msgs::PR2GripperEventDetectorActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
    s << std::endl;
    Printer< ::pr2_gripper_sensor_msgs::PR2GripperEventDetectorActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
    s << std::endl;
    Printer< ::pr2_gripper_sensor_msgs::PR2GripperEventDetectorActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PR2_GRIPPER_SENSOR_MSGS_MESSAGE_PR2GRIPPEREVENTDETECTORACTION_H
