// Generated by gencpp from file ml_classifiers/AddClassDataRequest.msg
// DO NOT EDIT!


#ifndef ML_CLASSIFIERS_MESSAGE_ADDCLASSDATAREQUEST_H
#define ML_CLASSIFIERS_MESSAGE_ADDCLASSDATAREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ml_classifiers/ClassDataPoint.h>

namespace ml_classifiers
{
template <class ContainerAllocator>
struct AddClassDataRequest_
{
  typedef AddClassDataRequest_<ContainerAllocator> Type;

  AddClassDataRequest_()
    : identifier()
    , data()  {
    }
  AddClassDataRequest_(const ContainerAllocator& _alloc)
    : identifier(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _identifier_type;
  _identifier_type identifier;

   typedef std::vector< ::ml_classifiers::ClassDataPoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::ml_classifiers::ClassDataPoint_<ContainerAllocator> >::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::ml_classifiers::AddClassDataRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ml_classifiers::AddClassDataRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddClassDataRequest_

typedef ::ml_classifiers::AddClassDataRequest_<std::allocator<void> > AddClassDataRequest;

typedef boost::shared_ptr< ::ml_classifiers::AddClassDataRequest > AddClassDataRequestPtr;
typedef boost::shared_ptr< ::ml_classifiers::AddClassDataRequest const> AddClassDataRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ml_classifiers::AddClassDataRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ml_classifiers::AddClassDataRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ml_classifiers

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/mathworks/devel/sbs/31/pmurali.Brobot.j1339814/matlab/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg'], 'ml_classifiers': ['/mathworks/home/pmurali/Documents/MNO/matlab_msg_gen_ros1/glnxa64/src/ml_classifiers/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ml_classifiers::AddClassDataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ml_classifiers::AddClassDataRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ml_classifiers::AddClassDataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ml_classifiers::AddClassDataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ml_classifiers::AddClassDataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ml_classifiers::AddClassDataRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ml_classifiers::AddClassDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "572733f6e77cd60bddc5c0b72307999c";
  }

  static const char* value(const ::ml_classifiers::AddClassDataRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x572733f6e77cd60bULL;
  static const uint64_t static_value2 = 0xddc5c0b72307999cULL;
};

template<class ContainerAllocator>
struct DataType< ::ml_classifiers::AddClassDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ml_classifiers/AddClassDataRequest";
  }

  static const char* value(const ::ml_classifiers::AddClassDataRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ml_classifiers::AddClassDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string identifier\n"
"ClassDataPoint[] data\n"
"\n"
"================================================================================\n"
"MSG: ml_classifiers/ClassDataPoint\n"
"string target_class\n"
"float64[] point\n"
;
  }

  static const char* value(const ::ml_classifiers::AddClassDataRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ml_classifiers::AddClassDataRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.identifier);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddClassDataRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ml_classifiers::AddClassDataRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ml_classifiers::AddClassDataRequest_<ContainerAllocator>& v)
  {
    s << indent << "identifier: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.identifier);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ml_classifiers::ClassDataPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ML_CLASSIFIERS_MESSAGE_ADDCLASSDATAREQUEST_H
