
classdef Mask < ros.Message
    %Mask MATLAB implementation of cob_object_detection_msgs/Mask
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'cob_object_detection_msgs/Mask' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'e1240778c6320b394ae629a7eb8c26ba' % The MD5 Checksum of the message definition
        PropertyList = { 'Roi' 'Mask_' } % List of non-constant message properties
        ROSPropertyList = { 'roi' 'mask' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.cob_object_detection_msgs.Rect' ...
            'ros.msg.sensor_msgs.Image' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Roi
        Mask_
    end
    methods
        function set.Roi(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.cob_object_detection_msgs.Rect'};
            validateattributes(val, validClasses, validAttributes, 'Mask', 'Roi')
            obj.Roi = val;
        end
        function set.Mask_(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msg.sensor_msgs.Image'};
            validateattributes(val, validClasses, validAttributes, 'Mask', 'Mask_')
            obj.Mask_ = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.cob_object_detection_msgs.Mask.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.cob_object_detection_msgs.Mask(strObj);
        end
    end
end
