
classdef Mesh < ros.Message
    %Mesh MATLAB implementation of shape_msgs/Mesh
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'shape_msgs/Mesh' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '1ffdae9486cd3316a121c578b47a85cc' % The MD5 Checksum of the message definition
        PropertyList = { 'Triangles' 'Vertices' } % List of non-constant message properties
        ROSPropertyList = { 'triangles' 'vertices' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.shape_msgs.MeshTriangle' ...
            'ros.msggen.geometry_msgs.Point' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Triangles
        Vertices
    end
    methods
        function set.Triangles(obj, val)
            if isempty(val)
                % Allow empty [] input
                val = ros.msggen.shape_msgs.MeshTriangle.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validClasses = {'ros.msggen.shape_msgs.MeshTriangle'};
            validateattributes(val, validClasses, validAttributes, 'Mesh', 'Triangles')
            obj.Triangles = val;
        end
        function set.Vertices(obj, val)
            if isempty(val)
                % Allow empty [] input
                val = ros.msggen.geometry_msgs.Point.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validClasses = {'ros.msggen.geometry_msgs.Point'};
            validateattributes(val, validClasses, validAttributes, 'Mesh', 'Vertices')
            obj.Vertices = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.shape_msgs.Mesh.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.shape_msgs.Mesh(strObj);
        end
    end
end
