// Generated by gencpp from file microstrain_3dmgx2_imu/AddOffset.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_3DMGX2_IMU_MESSAGE_ADDOFFSET_H
#define MICROSTRAIN_3DMGX2_IMU_MESSAGE_ADDOFFSET_H

#include <ros/service_traits.h>


#include <microstrain_3dmgx2_imu/AddOffsetRequest.h>
#include <microstrain_3dmgx2_imu/AddOffsetResponse.h>


namespace microstrain_3dmgx2_imu
{

struct AddOffset
{

typedef AddOffsetRequest Request;
typedef AddOffsetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddOffset
} // namespace microstrain_3dmgx2_imu


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::microstrain_3dmgx2_imu::AddOffset > {
  static const char* value()
  {
    return "f5dcf1246c1a25fcc69616e9d14c1482";
  }

  static const char* value(const ::microstrain_3dmgx2_imu::AddOffset&) { return value(); }
};

template<>
struct DataType< ::microstrain_3dmgx2_imu::AddOffset > {
  static const char* value()
  {
    return "microstrain_3dmgx2_imu/AddOffset";
  }

  static const char* value(const ::microstrain_3dmgx2_imu::AddOffset&) { return value(); }
};


// service_traits::MD5Sum< ::microstrain_3dmgx2_imu::AddOffsetRequest> should match 
// service_traits::MD5Sum< ::microstrain_3dmgx2_imu::AddOffset > 
template<>
struct MD5Sum< ::microstrain_3dmgx2_imu::AddOffsetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_3dmgx2_imu::AddOffset >::value();
  }
  static const char* value(const ::microstrain_3dmgx2_imu::AddOffsetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_3dmgx2_imu::AddOffsetRequest> should match 
// service_traits::DataType< ::microstrain_3dmgx2_imu::AddOffset > 
template<>
struct DataType< ::microstrain_3dmgx2_imu::AddOffsetRequest>
{
  static const char* value()
  {
    return DataType< ::microstrain_3dmgx2_imu::AddOffset >::value();
  }
  static const char* value(const ::microstrain_3dmgx2_imu::AddOffsetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::microstrain_3dmgx2_imu::AddOffsetResponse> should match 
// service_traits::MD5Sum< ::microstrain_3dmgx2_imu::AddOffset > 
template<>
struct MD5Sum< ::microstrain_3dmgx2_imu::AddOffsetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_3dmgx2_imu::AddOffset >::value();
  }
  static const char* value(const ::microstrain_3dmgx2_imu::AddOffsetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_3dmgx2_imu::AddOffsetResponse> should match 
// service_traits::DataType< ::microstrain_3dmgx2_imu::AddOffset > 
template<>
struct DataType< ::microstrain_3dmgx2_imu::AddOffsetResponse>
{
  static const char* value()
  {
    return DataType< ::microstrain_3dmgx2_imu::AddOffset >::value();
  }
  static const char* value(const ::microstrain_3dmgx2_imu::AddOffsetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MICROSTRAIN_3DMGX2_IMU_MESSAGE_ADDOFFSET_H
