function [prop, ParamInfo] = getMATLABPILProps()
%This class is for internal use only. It may be removed in the future.

%GETMATLABPILINFO Return MATLAB PIL properties.

% Copyright 2020 The MathWorks, Inc.

% Target version
propNum = 1;
prop(propNum).Name = 'TargetVersion';
prop(propNum).SetMethod = [];
prop(propNum).GetMethod = @ros.codertarget.internal.PropertyInfo.getTargetVersion;

% PackageMaintainer Name
propNum = propNum + 1;
prop(propNum).Name = 'PackageMaintainerName';
prop(propNum).SetMethod = @ros.codertarget.internal.PropertyInfo.setgetPackageMaintainerName;
prop(propNum).GetMethod = @ros.codertarget.internal.PropertyInfo.setgetPackageMaintainerName;

% PackageMaintainerEmail
propNum = propNum + 1;
prop(propNum).Name = 'PackageMaintainerEmail';
prop(propNum).SetMethod = @ros.codertarget.internal.PropertyInfo.setgetPackageMaintainerEmail;
prop(propNum).GetMethod = @ros.codertarget.internal.PropertyInfo.setgetPackageMaintainerEmail;

% PackageLicense
propNum = propNum + 1;
prop(propNum).Name = 'PackageLicense';
prop(propNum).SetMethod = @ros.codertarget.internal.PropertyInfo.setgetPackageLicense;
prop(propNum).GetMethod = @ros.codertarget.internal.PropertyInfo.setgetPackageLicense;

% PackageVersion
propNum = propNum + 1;
prop(propNum).Name = 'PackageVersion';
prop(propNum).SetMethod = @ros.codertarget.internal.PropertyInfo.setgetPackageVersion;
prop(propNum).GetMethod = @ros.codertarget.internal.PropertyInfo.setgetPackageVersion;

% Device
propNum = propNum + 1;
prop(propNum).Name = 'DeployTo';
prop(propNum).SetMethod = @ros.codertarget.internal.PropertyInfo.setgetDeployTo;
prop(propNum).GetMethod = @ros.codertarget.internal.PropertyInfo.setgetDeployTo;

% ROS folder
propNum = propNum + 1;
prop(propNum).Name = 'ROSFolder';
prop(propNum).SetMethod = @ros.codertarget.internal.PropertyInfo.setgetROSFolder;
prop(propNum).GetMethod = @ros.codertarget.internal.PropertyInfo.setgetROSFolder;

% Catkin workspace
propNum = propNum + 1;
prop(propNum).Name = 'CatkinWorkspace';
prop(propNum).SetMethod = @ros.codertarget.internal.PropertyInfo.setgetCatkinWorkspace;
prop(propNum).GetMethod = @ros.codertarget.internal.PropertyInfo.setgetCatkinWorkspace;

% Remote device address
propNum = propNum + 1;
prop(propNum).Name = 'RemoteDeviceAddress';
prop(propNum).SetMethod = @ros.codertarget.internal.PropertyInfo.setgetRemoteDeviceAddress;
prop(propNum).GetMethod = @ros.codertarget.internal.PropertyInfo.setgetRemoteDeviceAddress;

% Remote device username
propNum = propNum + 1;
prop(propNum).Name = 'RemoteDeviceUsername';
prop(propNum).SetMethod = @ros.codertarget.internal.PropertyInfo.setgetRemoteDeviceUsername;
prop(propNum).GetMethod = @ros.codertarget.internal.PropertyInfo.setgetRemoteDeviceUsername;

% Remote device password
propNum = propNum + 1;
prop(propNum).Name = 'RemoteDevicePassword';
prop(propNum).SetMethod = @ros.codertarget.internal.PropertyInfo.setgetRemoteDevicePassword;
prop(propNum).GetMethod = @ros.codertarget.internal.PropertyInfo.setgetRemoteDevicePassword;

% Build action
propNum = propNum + 1;
prop(propNum).Name = 'BuildAction';
prop(propNum).SetMethod = @ros.codertarget.internal.PropertyInfo.setgetBuildAction;
prop(propNum).GetMethod = @ros.codertarget.internal.PropertyInfo.setgetBuildAction;

% Parameter info for GUI widgets
pObj = i_createParameterInfoObject();
ParamInfo.Parameter{1} = pObj.Parameters{1};
ParamInfo.Parameter{2} = pObj.Parameters{2};
ParamInfo.Parameter{3} = pObj.Parameters{3};
ParamInfo.ParameterGroups = pObj.ParameterGroups;
end


% -------------------------------------------------------------------------
function p = i_createParameterInfoObject(~,~)
p = codertarget.parameter.ParameterInfo;
%% Package information
grp = message('ros:mlroscpp:codegen:ui_pkginfo_group').getString;
p.addParameter('Group',grp, ...
    'Name', message('ros:mlroscpp:codegen:ui_pkginfo_maintainername_label').getString, ...
    'Type','edit', ...
    'Tag','PackageMaintainerName', ...
    'Enabled','1', ...
    'Visible','1', ...
    'Value','ros.codertarget.internal.PropertyInfo.setgetPackageMaintainerName', ...
    'Data','', ...
    'RowSpan','[0,0]', ...
    'ColSpan','[1,3]', ...
    'Alignment','1', ...
    'DialogRefresh','0', ...
    'Storage','PackageMaintainerName', ...
    'DoNotStore','false', ...
    'Callback','ros.codertarget.internal.onPackageMaintainerNameChange', ...
    'SaveValueAsString','true', ...
    'Entries','', ...
    'ValueType','callback', ...
    'ValueRange','', ...
    'ToolTip','');
p.addParameter('Group', grp, ...
    'Name', message('ros:mlroscpp:codegen:ui_pkginfo_maintaineremail_label').getString, ...
    'Type','edit', ...
    'Tag','PackageMaintainerEmail', ...
    'Enabled','1', ...
    'Visible','1', ...
    'Value','ros.codertarget.internal.PropertyInfo.setgetPackageMaintainerEmail', ...
    'Data','', ...
    'RowSpan','[0,0]', ...
    'ColSpan','[1,3]', ...
    'Alignment','1', ...
    'DialogRefresh','0', ...
    'Storage','PackageMaintainerEmail', ...
    'DoNotStore','false', ...
    'Callback','ros.codertarget.internal.onPackageMaintainerEmailChange', ...
    'SaveValueAsString','true', ...
    'Entries','', ...
    'ValueType','callback', ...
    'ValueRange','', ...
    'ToolTip','');
p.addParameter('Group', grp, ...
    'Name', message('ros:mlroscpp:codegen:ui_pkginfo_license_label').getString, ...
    'Type','edit', ...
    'Tag','PackageLicense', ...
    'Enabled','1', ...
    'Visible','1', ...
    'Value','ros.codertarget.internal.PropertyInfo.setgetPackageLicense', ...
    'Data','', ...
    'RowSpan','[0,0]', ...
    'ColSpan','[1,3]', ...
    'Alignment','1', ...
    'DialogRefresh','0', ...
    'Storage','PackageLicense', ...
    'DoNotStore','false', ...
    'Callback','ros.codertarget.internal.onPackageLicenseChange', ...
    'SaveValueAsString','true', ...
    'Entries','', ...
    'ValueType','callback', ...
    'ValueRange','', ...
    'ToolTip','');
p.addParameter('Group', grp, ...
    'Name', message('ros:mlroscpp:codegen:ui_pkginfo_version_label').getString, ...
    'Type','edit', ...
    'Tag','PackageVersion', ...
    'Enabled','1', ...
    'Visible','1', ...
    'Value','ros.codertarget.internal.PropertyInfo.setgetPackageVersion', ...
    'Data','', ...
    'RowSpan','[0,0]', ...
    'ColSpan','[1,3]', ...
    'Alignment','1', ...
    'DialogRefresh','0', ...
    'Storage','PackageVersion', ...
    'DoNotStore','false', ...
    'Callback','ros.codertarget.internal.onPackageVersionChange', ...
    'SaveValueAsString','true', ...
    'Entries','', ...
    'ValueType','callback', ...
    'ValueRange','', ...
    'ToolTip','');
%% Device parameters
grp = message('ros:mlroscpp:codegen:ui_deviceparameters_group').getString;
p.addParameter('Group',grp, ...
    'Name', message('ros:mlroscpp:codegen:ui_deviceparameters_deployto').getString, ...
    'Type','combobox', ...
    'Tag','Deploy_to', ...
    'Enabled','1', ...
    'Visible','1', ...
    'Value', 'ros.codertarget.internal.PropertyInfo.setgetDeployTo', ...
    'Data','', ...
    'RowSpan', '[0,0]', ...
    'ColSpan','[1,3]', ...
    'Alignment','1', ...
    'DialogRefresh','0', ...
    'Storage','DeployTo', ...
    'DoNotStore','false', ...
    'Callback','ros.codertarget.internal.onDeployToChange', ...
    'SaveValueAsString','true', ...
    'Entries',[getString(message('ros:mlroscpp:codegen:Localhost')) ';',...
    getString(message('ros:mlroscpp:codegen:RemoteDevice'))], ...
    'ValueType','', ...
    'ValueRange','','ToolTip','');
p.addParameter('Group',grp, ...
    'Name', message('ros:mlroscpp:codegen:ui_deviceparameters_deployto_remotedeviceaddress').getString,...
    'Type','edit',...
    'Tag','Remote_device_address',...
    'Enabled','1',...
    'Visible','1',...
    'Value','ros.codertarget.internal.PropertyInfo.setgetRemoteDeviceAddress',...
    'Data','',...
    'RowSpan','[0,0]',...
    'ColSpan','[1,3]',...
    'Alignment','1',...
    'DialogRefresh','0',...
    'Storage','RemoteDeviceAddress',...
    'DoNotStore','false',...
    'Callback','ros.codertarget.internal.onRemoteDeviceAddressChange',...
    'SaveValueAsString','true',...
    'ValueType','callback',...
    'ValueRange','',...
    'ToolTip','');
p.addParameter('Group',grp, ...
    'Name', message('ros:mlroscpp:codegen:ui_deviceparameters_deployto_remotedeviceusername').getString,...
    'Type','edit',...
    'Tag','Remote_device_username',...
    'Enabled','1',...
    'Visible','1',...
    'Value','ros.codertarget.internal.PropertyInfo.setgetRemoteDeviceUsername',...
    'Data','',...
    'RowSpan','[0,0]',...
    'ColSpan','[1,3]',...
    'Alignment','1',...
    'DialogRefresh','0',...
    'Storage','RemoteDeviceUsername',...
    'DoNotStore','false',...
    'Callback','ros.codertarget.internal.onRemoteDeviceUsernameChange',...
    'SaveValueAsString','true',...
    'ValueType','callback',...
    'ValueRange','',...
    'ToolTip','');
p.addParameter('Group',grp, ...
    'Name', message('ros:mlroscpp:codegen:ui_deviceparameters_deployto_remotedevicepassword').getString,...
    'Type','edit',...
    'Tag','Remote_device_password',...
    'Enabled','1',...
    'Visible','1',...
    'Value','ros.codertarget.internal.PropertyInfo.setgetRemoteDevicePassword',...
    'Data','',...
    'RowSpan','[0,0]',...
    'ColSpan','[1,3]',...
    'Alignment','1',...
    'DialogRefresh','0',...
    'Storage','RemoteDevicePassword',...
    'DoNotStore','false',...
    'Callback','ros.codertarget.internal.onRemoteDevicePasswordChange',...
    'SaveValueAsString','true',...
    'ValueType','callback',...
    'ValueRange','',...
    'ToolTip','');
%% Build options
grp = message('ros:mlroscpp:codegen:ui_buildopts_group').getString;
p.addParameter('Group',grp, ...
    'Name', 'Build action:', ...
    'Type','combobox', ...
    'Tag','Build_action', ...
    'Enabled','1', ...
    'Visible','1', ...
    'Value', 'ros.codertarget.internal.PropertyInfo.setgetBuildAction', ...
    'Data','', ...
    'RowSpan', '[0,0]', ...
    'ColSpan','[1,3]', ...
    'Alignment','1', ...
    'DialogRefresh','0', ...
    'Storage','BuildAction', ...
    'DoNotStore','false', ...
    'Callback','ros.codertarget.internal.onBuildActionChange', ...
    'SaveValueAsString','true', ...
    'Entries',[getString(message('ros:mlroscpp:codegen:None')),';'...
    getString(message('ros:mlroscpp:codegen:Buildandload')),';'...
    getString(message('ros:mlroscpp:codegen:Buildandrun'))], ...
    'ValueType','', ...
    'ValueRange','','ToolTip','');
p.addParameter('Group',grp, ...
    'Name', 'ROS install folder:',...
    'Type','edit',...
    'Tag','ROSInstall',...
    'Enabled','1',...
    'Visible','1',...
    'Value','ros.codertarget.internal.PropertyInfo.setgetROSFolder',...
    'Data','',...
    'RowSpan','[0,0]',...
    'ColSpan','[1,3]',...
    'Alignment','1',...
    'DialogRefresh','0',...
    'Storage','ROSFolder',...
    'DoNotStore','false',...
    'Callback','ros.codertarget.internal.onROSFolderChange',...
    'SaveValueAsString','true',...
    'ValueType','callback',...
    'ValueRange','',...
    'ToolTip','');
p.addParameter('Group',grp, ...
    'Name', 'Catkin workspace:',...
    'Type','edit',...
    'Tag','ROSWorkspace',...
    'Enabled','1',...
    'Visible','1',...
    'Value','ros.codertarget.internal.PropertyInfo.setgetCatkinWorkspace',...
    'Data','',...
    'RowSpan','[0,0]',...
    'ColSpan','[1,3]',...
    'Alignment','1',...
    'DialogRefresh','0',...
    'Storage','CatkinWorkspace',...
    'DoNotStore','false',...
    'Callback','ros.codertarget.internal.onCatkinWorkspaceChange',...
    'SaveValueAsString','true',...
    'ValueType','callback',...
    'ValueRange','',...
    'ToolTip','');
end