// Generated by gencpp from file lizi/set_odom.msg
// DO NOT EDIT!


#ifndef LIZI_MESSAGE_SET_ODOM_H
#define LIZI_MESSAGE_SET_ODOM_H

#include <ros/service_traits.h>


#include <lizi/set_odomRequest.h>
#include <lizi/set_odomResponse.h>


namespace lizi
{

struct set_odom
{

typedef set_odomRequest Request;
typedef set_odomResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_odom
} // namespace lizi


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lizi::set_odom > {
  static const char* value()
  {
    return "a130bc60ee6513855dc62ea83fcc5b20";
  }

  static const char* value(const ::lizi::set_odom&) { return value(); }
};

template<>
struct DataType< ::lizi::set_odom > {
  static const char* value()
  {
    return "lizi/set_odom";
  }

  static const char* value(const ::lizi::set_odom&) { return value(); }
};


// service_traits::MD5Sum< ::lizi::set_odomRequest> should match 
// service_traits::MD5Sum< ::lizi::set_odom > 
template<>
struct MD5Sum< ::lizi::set_odomRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lizi::set_odom >::value();
  }
  static const char* value(const ::lizi::set_odomRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lizi::set_odomRequest> should match 
// service_traits::DataType< ::lizi::set_odom > 
template<>
struct DataType< ::lizi::set_odomRequest>
{
  static const char* value()
  {
    return DataType< ::lizi::set_odom >::value();
  }
  static const char* value(const ::lizi::set_odomRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lizi::set_odomResponse> should match 
// service_traits::MD5Sum< ::lizi::set_odom > 
template<>
struct MD5Sum< ::lizi::set_odomResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lizi::set_odom >::value();
  }
  static const char* value(const ::lizi::set_odomResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lizi::set_odomResponse> should match 
// service_traits::DataType< ::lizi::set_odom > 
template<>
struct DataType< ::lizi::set_odomResponse>
{
  static const char* value()
  {
    return DataType< ::lizi::set_odom >::value();
  }
  static const char* value(const ::lizi::set_odomResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LIZI_MESSAGE_SET_ODOM_H
