
classdef StopCapabilityResponse < ros.Message
    %StopCapabilityResponse MATLAB implementation of capabilities/StopCapabilityResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'capabilities/StopCapabilityResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '6ccdb752b565be6d250259ff3d0c7ea1' % The MD5 Checksum of the message definition
        PropertyList = { 'Successful' } % List of non-constant message properties
        ROSPropertyList = { 'successful' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Successful
    end
    methods
        function set.Successful(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'StopCapabilityResponse', 'Successful');
            obj.Successful = logical(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.capabilities.StopCapabilityResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.capabilities.StopCapabilityResponse(strObj);
        end
    end
end
