// Generated by gencpp from file um6/ResetRequest.msg
// DO NOT EDIT!


#ifndef UM6_MESSAGE_RESETREQUEST_H
#define UM6_MESSAGE_RESETREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace um6
{
template <class ContainerAllocator>
struct ResetRequest_
{
  typedef ResetRequest_<ContainerAllocator> Type;

  ResetRequest_()
    : zero_gyros(false)
    , reset_ekf(false)
    , set_mag_ref(false)
    , set_accel_ref(false)  {
    }
  ResetRequest_(const ContainerAllocator& _alloc)
    : zero_gyros(false)
    , reset_ekf(false)
    , set_mag_ref(false)
    , set_accel_ref(false)  {
  (void)_alloc;
    }



   typedef uint8_t _zero_gyros_type;
  _zero_gyros_type zero_gyros;

   typedef uint8_t _reset_ekf_type;
  _reset_ekf_type reset_ekf;

   typedef uint8_t _set_mag_ref_type;
  _set_mag_ref_type set_mag_ref;

   typedef uint8_t _set_accel_ref_type;
  _set_accel_ref_type set_accel_ref;





  typedef boost::shared_ptr< ::um6::ResetRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::um6::ResetRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ResetRequest_

typedef ::um6::ResetRequest_<std::allocator<void> > ResetRequest;

typedef boost::shared_ptr< ::um6::ResetRequest > ResetRequestPtr;
typedef boost::shared_ptr< ::um6::ResetRequest const> ResetRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::um6::ResetRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::um6::ResetRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace um6

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/mathworks/devel/sbs/31/pmurali.Brobot.j1339814/matlab/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::um6::ResetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::um6::ResetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::um6::ResetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::um6::ResetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::um6::ResetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::um6::ResetRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::um6::ResetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "88aed859f96ffbc3fdce434a0b135bb3";
  }

  static const char* value(const ::um6::ResetRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x88aed859f96ffbc3ULL;
  static const uint64_t static_value2 = 0xfdce434a0b135bb3ULL;
};

template<class ContainerAllocator>
struct DataType< ::um6::ResetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "um6/ResetRequest";
  }

  static const char* value(const ::um6::ResetRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::um6::ResetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool zero_gyros\n"
"bool reset_ekf\n"
"bool set_mag_ref\n"
"bool set_accel_ref\n"
;
  }

  static const char* value(const ::um6::ResetRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::um6::ResetRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.zero_gyros);
      stream.next(m.reset_ekf);
      stream.next(m.set_mag_ref);
      stream.next(m.set_accel_ref);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResetRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::um6::ResetRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::um6::ResetRequest_<ContainerAllocator>& v)
  {
    s << indent << "zero_gyros: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.zero_gyros);
    s << indent << "reset_ekf: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reset_ekf);
    s << indent << "set_mag_ref: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.set_mag_ref);
    s << indent << "set_accel_ref: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.set_accel_ref);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UM6_MESSAGE_RESETREQUEST_H
