// Generated by gencpp from file cob_base_drive_chain/ElmoRecorderReadoutRequest.msg
// DO NOT EDIT!


#ifndef COB_BASE_DRIVE_CHAIN_MESSAGE_ELMORECORDERREADOUTREQUEST_H
#define COB_BASE_DRIVE_CHAIN_MESSAGE_ELMORECORDERREADOUTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cob_base_drive_chain
{
template <class ContainerAllocator>
struct ElmoRecorderReadoutRequest_
{
  typedef ElmoRecorderReadoutRequest_<ContainerAllocator> Type;

  ElmoRecorderReadoutRequest_()
    : subindex(0)
    , fileprefix()  {
    }
  ElmoRecorderReadoutRequest_(const ContainerAllocator& _alloc)
    : subindex(0)
    , fileprefix(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _subindex_type;
  _subindex_type subindex;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _fileprefix_type;
  _fileprefix_type fileprefix;





  typedef boost::shared_ptr< ::cob_base_drive_chain::ElmoRecorderReadoutRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cob_base_drive_chain::ElmoRecorderReadoutRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ElmoRecorderReadoutRequest_

typedef ::cob_base_drive_chain::ElmoRecorderReadoutRequest_<std::allocator<void> > ElmoRecorderReadoutRequest;

typedef boost::shared_ptr< ::cob_base_drive_chain::ElmoRecorderReadoutRequest > ElmoRecorderReadoutRequestPtr;
typedef boost::shared_ptr< ::cob_base_drive_chain::ElmoRecorderReadoutRequest const> ElmoRecorderReadoutRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cob_base_drive_chain::ElmoRecorderReadoutRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cob_base_drive_chain::ElmoRecorderReadoutRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cob_base_drive_chain

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/mathworks/devel/sbs/31/pmurali.Brobot.j1339814/matlab/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cob_base_drive_chain::ElmoRecorderReadoutRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cob_base_drive_chain::ElmoRecorderReadoutRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cob_base_drive_chain::ElmoRecorderReadoutRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cob_base_drive_chain::ElmoRecorderReadoutRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cob_base_drive_chain::ElmoRecorderReadoutRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cob_base_drive_chain::ElmoRecorderReadoutRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cob_base_drive_chain::ElmoRecorderReadoutRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dd88752641c6995eb674ed67be4e41d1";
  }

  static const char* value(const ::cob_base_drive_chain::ElmoRecorderReadoutRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdd88752641c6995eULL;
  static const uint64_t static_value2 = 0xb674ed67be4e41d1ULL;
};

template<class ContainerAllocator>
struct DataType< ::cob_base_drive_chain::ElmoRecorderReadoutRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cob_base_drive_chain/ElmoRecorderReadoutRequest";
  }

  static const char* value(const ::cob_base_drive_chain::ElmoRecorderReadoutRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cob_base_drive_chain::ElmoRecorderReadoutRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"int64 subindex\n"
"\n"
"\n"
"\n"
"string fileprefix\n"
"\n"
;
  }

  static const char* value(const ::cob_base_drive_chain::ElmoRecorderReadoutRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cob_base_drive_chain::ElmoRecorderReadoutRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.subindex);
      stream.next(m.fileprefix);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ElmoRecorderReadoutRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cob_base_drive_chain::ElmoRecorderReadoutRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cob_base_drive_chain::ElmoRecorderReadoutRequest_<ContainerAllocator>& v)
  {
    s << indent << "subindex: ";
    Printer<int64_t>::stream(s, indent + "  ", v.subindex);
    s << indent << "fileprefix: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.fileprefix);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COB_BASE_DRIVE_CHAIN_MESSAGE_ELMORECORDERREADOUTREQUEST_H
