// Generated by gencpp from file rocon_service_pair_msgs/TestiesRequest.msg
// DO NOT EDIT!


#ifndef ROCON_SERVICE_PAIR_MSGS_MESSAGE_TESTIESREQUEST_H
#define ROCON_SERVICE_PAIR_MSGS_MESSAGE_TESTIESREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rocon_service_pair_msgs
{
template <class ContainerAllocator>
struct TestiesRequest_
{
  typedef TestiesRequest_<ContainerAllocator> Type;

  TestiesRequest_()
    : data()  {
    }
  TestiesRequest_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::rocon_service_pair_msgs::TestiesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rocon_service_pair_msgs::TestiesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TestiesRequest_

typedef ::rocon_service_pair_msgs::TestiesRequest_<std::allocator<void> > TestiesRequest;

typedef boost::shared_ptr< ::rocon_service_pair_msgs::TestiesRequest > TestiesRequestPtr;
typedef boost::shared_ptr< ::rocon_service_pair_msgs::TestiesRequest const> TestiesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rocon_service_pair_msgs::TestiesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rocon_service_pair_msgs::TestiesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rocon_service_pair_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/mathworks/devel/sbs/31/pmurali.Brobot.j1329247.2/matlab/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg'], 'rocon_service_pair_msgs': ['/mathworks/home/pmurali/Documents/Working/matlab_msg_gen_ros1/glnxa64/src/rocon_service_pair_msgs/msg'], 'uuid_msgs': ['/mathworks/home/pmurali/Documents/Working/matlab_msg_gen_ros1/glnxa64/src/uuid_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rocon_service_pair_msgs::TestiesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rocon_service_pair_msgs::TestiesRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rocon_service_pair_msgs::TestiesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rocon_service_pair_msgs::TestiesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rocon_service_pair_msgs::TestiesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rocon_service_pair_msgs::TestiesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rocon_service_pair_msgs::TestiesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "992ce8a1687cec8c8bd883ec73ca41d1";
  }

  static const char* value(const ::rocon_service_pair_msgs::TestiesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x992ce8a1687cec8cULL;
  static const uint64_t static_value2 = 0x8bd883ec73ca41d1ULL;
};

template<class ContainerAllocator>
struct DataType< ::rocon_service_pair_msgs::TestiesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rocon_service_pair_msgs/TestiesRequest";
  }

  static const char* value(const ::rocon_service_pair_msgs::TestiesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rocon_service_pair_msgs::TestiesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string data\n"
;
  }

  static const char* value(const ::rocon_service_pair_msgs::TestiesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rocon_service_pair_msgs::TestiesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TestiesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rocon_service_pair_msgs::TestiesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rocon_service_pair_msgs::TestiesRequest_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROCON_SERVICE_PAIR_MSGS_MESSAGE_TESTIESREQUEST_H
