// Generated by gencpp from file sr_robot_msgs/SetDebugData.msg
// DO NOT EDIT!


#ifndef SR_ROBOT_MSGS_MESSAGE_SETDEBUGDATA_H
#define SR_ROBOT_MSGS_MESSAGE_SETDEBUGDATA_H

#include <ros/service_traits.h>


#include <sr_robot_msgs/SetDebugDataRequest.h>
#include <sr_robot_msgs/SetDebugDataResponse.h>


namespace sr_robot_msgs
{

struct SetDebugData
{

typedef SetDebugDataRequest Request;
typedef SetDebugDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetDebugData
} // namespace sr_robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sr_robot_msgs::SetDebugData > {
  static const char* value()
  {
    return "7e92428f248882f525037fe3b24dbbf1";
  }

  static const char* value(const ::sr_robot_msgs::SetDebugData&) { return value(); }
};

template<>
struct DataType< ::sr_robot_msgs::SetDebugData > {
  static const char* value()
  {
    return "sr_robot_msgs/SetDebugData";
  }

  static const char* value(const ::sr_robot_msgs::SetDebugData&) { return value(); }
};


// service_traits::MD5Sum< ::sr_robot_msgs::SetDebugDataRequest> should match 
// service_traits::MD5Sum< ::sr_robot_msgs::SetDebugData > 
template<>
struct MD5Sum< ::sr_robot_msgs::SetDebugDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sr_robot_msgs::SetDebugData >::value();
  }
  static const char* value(const ::sr_robot_msgs::SetDebugDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sr_robot_msgs::SetDebugDataRequest> should match 
// service_traits::DataType< ::sr_robot_msgs::SetDebugData > 
template<>
struct DataType< ::sr_robot_msgs::SetDebugDataRequest>
{
  static const char* value()
  {
    return DataType< ::sr_robot_msgs::SetDebugData >::value();
  }
  static const char* value(const ::sr_robot_msgs::SetDebugDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sr_robot_msgs::SetDebugDataResponse> should match 
// service_traits::MD5Sum< ::sr_robot_msgs::SetDebugData > 
template<>
struct MD5Sum< ::sr_robot_msgs::SetDebugDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sr_robot_msgs::SetDebugData >::value();
  }
  static const char* value(const ::sr_robot_msgs::SetDebugDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sr_robot_msgs::SetDebugDataResponse> should match 
// service_traits::DataType< ::sr_robot_msgs::SetDebugData > 
template<>
struct DataType< ::sr_robot_msgs::SetDebugDataResponse>
{
  static const char* value()
  {
    return DataType< ::sr_robot_msgs::SetDebugData >::value();
  }
  static const char* value(const ::sr_robot_msgs::SetDebugDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SR_ROBOT_MSGS_MESSAGE_SETDEBUGDATA_H
