// Generated by gencpp from file sr_robot_msgs/SetPidGains.msg
// DO NOT EDIT!


#ifndef SR_ROBOT_MSGS_MESSAGE_SETPIDGAINS_H
#define SR_ROBOT_MSGS_MESSAGE_SETPIDGAINS_H

#include <ros/service_traits.h>


#include <sr_robot_msgs/SetPidGainsRequest.h>
#include <sr_robot_msgs/SetPidGainsResponse.h>


namespace sr_robot_msgs
{

struct SetPidGains
{

typedef SetPidGainsRequest Request;
typedef SetPidGainsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPidGains
} // namespace sr_robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sr_robot_msgs::SetPidGains > {
  static const char* value()
  {
    return "f9c5176e998bba30344c4892f975be3a";
  }

  static const char* value(const ::sr_robot_msgs::SetPidGains&) { return value(); }
};

template<>
struct DataType< ::sr_robot_msgs::SetPidGains > {
  static const char* value()
  {
    return "sr_robot_msgs/SetPidGains";
  }

  static const char* value(const ::sr_robot_msgs::SetPidGains&) { return value(); }
};


// service_traits::MD5Sum< ::sr_robot_msgs::SetPidGainsRequest> should match 
// service_traits::MD5Sum< ::sr_robot_msgs::SetPidGains > 
template<>
struct MD5Sum< ::sr_robot_msgs::SetPidGainsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sr_robot_msgs::SetPidGains >::value();
  }
  static const char* value(const ::sr_robot_msgs::SetPidGainsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sr_robot_msgs::SetPidGainsRequest> should match 
// service_traits::DataType< ::sr_robot_msgs::SetPidGains > 
template<>
struct DataType< ::sr_robot_msgs::SetPidGainsRequest>
{
  static const char* value()
  {
    return DataType< ::sr_robot_msgs::SetPidGains >::value();
  }
  static const char* value(const ::sr_robot_msgs::SetPidGainsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sr_robot_msgs::SetPidGainsResponse> should match 
// service_traits::MD5Sum< ::sr_robot_msgs::SetPidGains > 
template<>
struct MD5Sum< ::sr_robot_msgs::SetPidGainsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sr_robot_msgs::SetPidGains >::value();
  }
  static const char* value(const ::sr_robot_msgs::SetPidGainsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sr_robot_msgs::SetPidGainsResponse> should match 
// service_traits::DataType< ::sr_robot_msgs::SetPidGains > 
template<>
struct DataType< ::sr_robot_msgs::SetPidGainsResponse>
{
  static const char* value()
  {
    return DataType< ::sr_robot_msgs::SetPidGains >::value();
  }
  static const char* value(const ::sr_robot_msgs::SetPidGainsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SR_ROBOT_MSGS_MESSAGE_SETPIDGAINS_H
