# Constants that define Rovio head positions based on the Rovio API
int8 HEAD_UP=11
int8 HEAD_DOWN=12
int8 HEAD_MIDDLE=13

int8 head_pos
---
# Constants that define the response codes based on the Rovio API
int8 SUCCESS=0
int8 FAILURE=1
int8 ROBOT_BUSY=2
int8 FEATURE_NOT_IMPLEMENTED=3
int8 UNKNOWN_CGI_ACTION=4
int8 NO_NS_SIGNAL=5
int8 NO_EMPTY_PATH_AVAILABLE=6
int8 FAILED_TO_READ_PATH=7
int8 PATH_BASEADDRESS_NOT_INITIALIZED=8
int8 PATH_NOT_FOUND=9
int8 PATH_NAME_NOT_SPECIFIED=10
int8 NOT_RECORDING_PATH=11
int8 FLASH_NOT_INITIALIZED=12
int8 FAILED_TO_DELETE_PATH=13
int8 FAILED_TO_READ_FROM_FLASH=14
int8 FAILED_TO_WRITE_TO_FLASH=15
int8 FLASH_NOT_READY=16
int8 NO_MEMORY_AVAILABLE=17
int8 NO_MCU_PORT_AVAILABLE=18
int8 NO_NS_PORT_AVAILABLE=19
int8 NS_PACKET_CHECKSUM_ERROR=20
int8 NS_UART_READ_ERROR=21
int8 PARAMETER_OUTOFRANGE=22
int8 NO_PARAMETER=23

int8 response # Return the response code from the Rovio
