
classdef FileEntry < ros.Message
    %FileEntry MATLAB implementation of mavros_msgs/FileEntry
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'mavros_msgs/FileEntry' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '5ed706bccb946c5b3a5087569cc53ac3' % The MD5 Checksum of the message definition
        PropertyList = { 'Name' 'Type' 'Size' } % List of non-constant message properties
        ROSPropertyList = { 'name' 'type' 'size' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
        TYPEFILE = uint8(0)
        TYPEDIRECTORY = uint8(1)
    end
    properties
        Name
        Type
        Size
    end
    methods
        function set.Name(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'FileEntry', 'Name');
            obj.Name = char(val);
        end
        function set.Type(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'FileEntry', 'Type');
            obj.Type = uint8(val);
        end
        function set.Size(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'FileEntry', 'Size');
            obj.Size = uint64(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.mavros_msgs.FileEntry.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.mavros_msgs.FileEntry(strObj);
        end
    end
end
