
classdef MessageIntervalRequest < ros.Message
    %MessageIntervalRequest MATLAB implementation of mavros_msgs/MessageIntervalRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'mavros_msgs/MessageIntervalRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'e0211a7928924521de24f3981706be52' % The MD5 Checksum of the message definition
        PropertyList = { 'MessageId' 'MessageRate' } % List of non-constant message properties
        ROSPropertyList = { 'message_id' 'message_rate' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        MessageId
        MessageRate
    end
    methods
        function set.MessageId(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'MessageIntervalRequest', 'MessageId');
            obj.MessageId = uint32(val);
        end
        function set.MessageRate(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'MessageIntervalRequest', 'MessageRate');
            obj.MessageRate = single(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.mavros_msgs.MessageIntervalRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.mavros_msgs.MessageIntervalRequest(strObj);
        end
    end
end
