
classdef ParamValue < ros.Message
    %ParamValue MATLAB implementation of mavros_msgs/ParamValue
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'mavros_msgs/ParamValue' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'e2cb1c7a0f6ef0c62d450cd9362c980d' % The MD5 Checksum of the message definition
        PropertyList = { 'Integer' 'Real' } % List of non-constant message properties
        ROSPropertyList = { 'integer' 'real' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Integer
        Real
    end
    methods
        function set.Integer(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ParamValue', 'Integer');
            obj.Integer = int64(val);
        end
        function set.Real(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ParamValue', 'Real');
            obj.Real = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.mavros_msgs.ParamValue.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.mavros_msgs.ParamValue(strObj);
        end
    end
end
