
classdef Joy < ros.Message
    %Joy MATLAB implementation of sensor_msgs/Joy
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'sensor_msgs/Joy' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '5a9ea5f83505693b71e785041e67a8bb' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'Axes' 'Buttons' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'axes' 'buttons' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Header
        Axes
        Buttons
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'Joy', 'Header')
            obj.Header = val;
        end
        function set.Axes(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = single.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'Joy', 'Axes');
            obj.Axes = single(val);
        end
        function set.Buttons(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = int32.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'Joy', 'Buttons');
            obj.Buttons = int32(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.sensor_msgs.Joy.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.sensor_msgs.Joy(strObj);
        end
    end
end
