// Generated by gencpp from file zeroconf_msgs/RemoveListener.msg
// DO NOT EDIT!


#ifndef ZEROCONF_MSGS_MESSAGE_REMOVELISTENER_H
#define ZEROCONF_MSGS_MESSAGE_REMOVELISTENER_H

#include <ros/service_traits.h>


#include <zeroconf_msgs/RemoveListenerRequest.h>
#include <zeroconf_msgs/RemoveListenerResponse.h>


namespace zeroconf_msgs
{

struct RemoveListener
{

typedef RemoveListenerRequest Request;
typedef RemoveListenerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RemoveListener
} // namespace zeroconf_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::zeroconf_msgs::RemoveListener > {
  static const char* value()
  {
    return "05d7490b40a920d3a0ffcc1ebf3a0889";
  }

  static const char* value(const ::zeroconf_msgs::RemoveListener&) { return value(); }
};

template<>
struct DataType< ::zeroconf_msgs::RemoveListener > {
  static const char* value()
  {
    return "zeroconf_msgs/RemoveListener";
  }

  static const char* value(const ::zeroconf_msgs::RemoveListener&) { return value(); }
};


// service_traits::MD5Sum< ::zeroconf_msgs::RemoveListenerRequest> should match 
// service_traits::MD5Sum< ::zeroconf_msgs::RemoveListener > 
template<>
struct MD5Sum< ::zeroconf_msgs::RemoveListenerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::zeroconf_msgs::RemoveListener >::value();
  }
  static const char* value(const ::zeroconf_msgs::RemoveListenerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::zeroconf_msgs::RemoveListenerRequest> should match 
// service_traits::DataType< ::zeroconf_msgs::RemoveListener > 
template<>
struct DataType< ::zeroconf_msgs::RemoveListenerRequest>
{
  static const char* value()
  {
    return DataType< ::zeroconf_msgs::RemoveListener >::value();
  }
  static const char* value(const ::zeroconf_msgs::RemoveListenerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::zeroconf_msgs::RemoveListenerResponse> should match 
// service_traits::MD5Sum< ::zeroconf_msgs::RemoveListener > 
template<>
struct MD5Sum< ::zeroconf_msgs::RemoveListenerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::zeroconf_msgs::RemoveListener >::value();
  }
  static const char* value(const ::zeroconf_msgs::RemoveListenerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::zeroconf_msgs::RemoveListenerResponse> should match 
// service_traits::DataType< ::zeroconf_msgs::RemoveListener > 
template<>
struct DataType< ::zeroconf_msgs::RemoveListenerResponse>
{
  static const char* value()
  {
    return DataType< ::zeroconf_msgs::RemoveListener >::value();
  }
  static const char* value(const ::zeroconf_msgs::RemoveListenerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ZEROCONF_MSGS_MESSAGE_REMOVELISTENER_H
