function [SM,WCU,INFO] = robNoBlocks()
% Populates ROB* outputs for systems with no blocks.

%   Copyright 2004-2015 The MathWorks, Inc.
WCU = struct;
SM = struct('LowerBound',Inf,...
   'UpperBound',Inf,...
   'CriticalFrequency',NaN);
INFO = struct(...
   'Model',[],...
   'Frequency',NaN,...
   'Bounds',Inf(1,2),...
   'WorstPerturbation',WCU,...
   'Sensitivity',struct);