
classdef DigitalInputEvent < ros.Message
    %DigitalInputEvent MATLAB implementation of kobuki_msgs/DigitalInputEvent
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'kobuki_msgs/DigitalInputEvent' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '93da823c8b121f8a3940ef3830c58e44' % The MD5 Checksum of the message definition
        PropertyList = { 'Values' } % List of non-constant message properties
        ROSPropertyList = { 'values' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Values
    end
    methods
        function set.Values(obj, val)
            validClasses = {'logical', 'numeric'};
            val = val(:);
            validAttributes = {'vector', 'numel', 4};
            validateattributes(val, validClasses, validAttributes, 'DigitalInputEvent', 'Values');
            obj.Values = logical(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.kobuki_msgs.DigitalInputEvent.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.kobuki_msgs.DigitalInputEvent(strObj);
        end
    end
end
