// Generated by gencpp from file concert_msgs/StopSolution.msg
// DO NOT EDIT!


#ifndef CONCERT_MSGS_MESSAGE_STOPSOLUTION_H
#define CONCERT_MSGS_MESSAGE_STOPSOLUTION_H

#include <ros/service_traits.h>


#include <concert_msgs/StopSolutionRequest.h>
#include <concert_msgs/StopSolutionResponse.h>


namespace concert_msgs
{

struct StopSolution
{

typedef StopSolutionRequest Request;
typedef StopSolutionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StopSolution
} // namespace concert_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::concert_msgs::StopSolution > {
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::concert_msgs::StopSolution&) { return value(); }
};

template<>
struct DataType< ::concert_msgs::StopSolution > {
  static const char* value()
  {
    return "concert_msgs/StopSolution";
  }

  static const char* value(const ::concert_msgs::StopSolution&) { return value(); }
};


// service_traits::MD5Sum< ::concert_msgs::StopSolutionRequest> should match 
// service_traits::MD5Sum< ::concert_msgs::StopSolution > 
template<>
struct MD5Sum< ::concert_msgs::StopSolutionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::concert_msgs::StopSolution >::value();
  }
  static const char* value(const ::concert_msgs::StopSolutionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::concert_msgs::StopSolutionRequest> should match 
// service_traits::DataType< ::concert_msgs::StopSolution > 
template<>
struct DataType< ::concert_msgs::StopSolutionRequest>
{
  static const char* value()
  {
    return DataType< ::concert_msgs::StopSolution >::value();
  }
  static const char* value(const ::concert_msgs::StopSolutionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::concert_msgs::StopSolutionResponse> should match 
// service_traits::MD5Sum< ::concert_msgs::StopSolution > 
template<>
struct MD5Sum< ::concert_msgs::StopSolutionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::concert_msgs::StopSolution >::value();
  }
  static const char* value(const ::concert_msgs::StopSolutionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::concert_msgs::StopSolutionResponse> should match 
// service_traits::DataType< ::concert_msgs::StopSolution > 
template<>
struct DataType< ::concert_msgs::StopSolutionResponse>
{
  static const char* value()
  {
    return DataType< ::concert_msgs::StopSolution >::value();
  }
  static const char* value(const ::concert_msgs::StopSolutionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONCERT_MSGS_MESSAGE_STOPSOLUTION_H
