
classdef OpenCameraRequest < ros.Message
    %OpenCameraRequest MATLAB implementation of baxter_core_msgs/OpenCameraRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'baxter_core_msgs/OpenCameraRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'c4194eee32741c5a98ef8da9666fa6c9' % The MD5 Checksum of the message definition
        PropertyList = { 'Settings' 'Name' } % List of non-constant message properties
        ROSPropertyList = { 'settings' 'name' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.baxter_core_msgs.CameraSettings' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Settings
        Name
    end
    methods
        function set.Settings(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.baxter_core_msgs.CameraSettings'};
            validateattributes(val, validClasses, validAttributes, 'OpenCameraRequest', 'Settings')
            obj.Settings = val;
        end
        function set.Name(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'OpenCameraRequest', 'Name');
            obj.Name = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.baxter_core_msgs.OpenCameraRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.baxter_core_msgs.OpenCameraRequest(strObj);
        end
    end
end
