
classdef navdata_wind_speed < ros.Message
    %navdata_wind_speed MATLAB implementation of ardrone_autonomy/navdata_wind_speed
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'ardrone_autonomy/navdata_wind_speed' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '2cc5c1e9675c330dd38261e958a136d3' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'DroneTime' 'Tag' 'Size' 'WindSpeed' 'WindAngle' 'WindCompensationTheta' 'WindCompensationPhi' 'StateX1' 'StateX2' 'StateX3' 'StateX4' 'StateX5' 'StateX6' 'MagnetoDebug1' 'MagnetoDebug2' 'MagnetoDebug3' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'drone_time' 'tag' 'size' 'wind_speed' 'wind_angle' 'wind_compensation_theta' 'wind_compensation_phi' 'state_x1' 'state_x2' 'state_x3' 'state_x4' 'state_x5' 'state_x6' 'magneto_debug1' 'magneto_debug2' 'magneto_debug3' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Header
        DroneTime
        Tag
        Size
        WindSpeed
        WindAngle
        WindCompensationTheta
        WindCompensationPhi
        StateX1
        StateX2
        StateX3
        StateX4
        StateX5
        StateX6
        MagnetoDebug1
        MagnetoDebug2
        MagnetoDebug3
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'navdata_wind_speed', 'Header')
            obj.Header = val;
        end
        function set.DroneTime(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'navdata_wind_speed', 'DroneTime');
            obj.DroneTime = double(val);
        end
        function set.Tag(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'navdata_wind_speed', 'Tag');
            obj.Tag = uint16(val);
        end
        function set.Size(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'navdata_wind_speed', 'Size');
            obj.Size = uint16(val);
        end
        function set.WindSpeed(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'navdata_wind_speed', 'WindSpeed');
            obj.WindSpeed = single(val);
        end
        function set.WindAngle(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'navdata_wind_speed', 'WindAngle');
            obj.WindAngle = single(val);
        end
        function set.WindCompensationTheta(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'navdata_wind_speed', 'WindCompensationTheta');
            obj.WindCompensationTheta = single(val);
        end
        function set.WindCompensationPhi(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'navdata_wind_speed', 'WindCompensationPhi');
            obj.WindCompensationPhi = single(val);
        end
        function set.StateX1(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'navdata_wind_speed', 'StateX1');
            obj.StateX1 = single(val);
        end
        function set.StateX2(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'navdata_wind_speed', 'StateX2');
            obj.StateX2 = single(val);
        end
        function set.StateX3(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'navdata_wind_speed', 'StateX3');
            obj.StateX3 = single(val);
        end
        function set.StateX4(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'navdata_wind_speed', 'StateX4');
            obj.StateX4 = single(val);
        end
        function set.StateX5(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'navdata_wind_speed', 'StateX5');
            obj.StateX5 = single(val);
        end
        function set.StateX6(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'navdata_wind_speed', 'StateX6');
            obj.StateX6 = single(val);
        end
        function set.MagnetoDebug1(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'navdata_wind_speed', 'MagnetoDebug1');
            obj.MagnetoDebug1 = single(val);
        end
        function set.MagnetoDebug2(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'navdata_wind_speed', 'MagnetoDebug2');
            obj.MagnetoDebug2 = single(val);
        end
        function set.MagnetoDebug3(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'navdata_wind_speed', 'MagnetoDebug3');
            obj.MagnetoDebug3 = single(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.ardrone_autonomy.navdata_wind_speed.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.ardrone_autonomy.navdata_wind_speed(strObj);
        end
    end
end
