
classdef DesignatorRequest < ros.Message
    %DesignatorRequest MATLAB implementation of designator_integration_msgs/DesignatorRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'designator_integration_msgs/DesignatorRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '77556cd59d6b76ac1356dd3ccf246560' % The MD5 Checksum of the message definition
        PropertyList = { 'Designator' } % List of non-constant message properties
        ROSPropertyList = { 'designator' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.designator_integration_msgs.Designator' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Designator
    end
    methods
        function set.Designator(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.designator_integration_msgs.Designator'};
            validateattributes(val, validClasses, validAttributes, 'DesignatorRequest', 'Designator')
            obj.Designator = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.designator_integration_msgs.DesignatorRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.designator_integration_msgs.DesignatorRequest(strObj);
        end
    end
end
