classdef ImageEncoding
%This class is for internal use only. It may be removed in the future.

%ImageEncoding Data class for image encodings
%   This class defines the characteristics of each encoding.

%   Copyright 2017-2020 The MathWorks, Inc.

%#codegen

    properties (Constant)

        %AllEncodings
        AllEncodings = { 'rgb8', 'rgba8', 'rgb16', 'rgba16', ...
                         'bgr8', 'bgra8', 'bgr16', 'bgra16', 'mono8', 'mono16', ...
                         '32fc1', '32fc2', '32fc3', '32fc4', ...
                         '64fc1', '64fc2', '64fc3', '64fc4', ...
                         '8uc1', '8uc2', '8uc3', '8uc4', ...
                         '8sc1', '8sc2', '8sc3', '8sc4', ...
                         '16uc1', '16uc2', '16uc3', '16uc4', ...
                         '16sc1', '16sc2', '16sc3', '16sc4', ...
                         '32sc1', '32sc2', '32sc3', '32sc4', ...
                         'bayer_rggb8', 'bayer_bggr8', 'bayer_gbrg8', 'bayer_grbg8', ...
                         'bayer_rggb16', 'bayer_bggr16', 'bayer_gbrg16', 'bayer_grbg16'}


        %NonBayerEncodings
        NonBayerEncodings = ros.msg.sensor_msgs.internal.ImageEncoding.nonBayerEncodings();

        %BayerEncodings
        BayerEncodings = ros.msg.sensor_msgs.internal.ImageEncoding.bayerEncodings();

        %AlphaEncodings
        AlphaEncodings = ros.msg.sensor_msgs.internal.ImageEncoding.alphaEncodings();
    end

    methods (Static)
        function out = nonBayerEncodings()
            names = ros.msg.sensor_msgs.internal.ImageEncoding.AllEncodings;
            encodings = cellfun( ...
                @(enc)ros.msg.sensor_msgs.internal.ImageEncoding.info(enc), ...
                names, 'UniformOutput', false);
            idx = cellfun(@(enc) ~enc.IsBayer, encodings);
            out = cellfun(@(enc) enc.Name, encodings(idx), ...
                          'UniformOutput', false);
        end

        function out = bayerEncodings()
            names = ros.msg.sensor_msgs.internal.ImageEncoding.AllEncodings;
            encodings = cellfun( ...
                @(enc)ros.msg.sensor_msgs.internal.ImageEncoding.info(enc), ...
                names, 'UniformOutput', false);
            idx = cellfun(@(enc) enc.IsBayer, encodings);
            out = cellfun(@(enc) enc.Name, encodings(idx), ...
                          'UniformOutput', false);
        end

        function out = alphaEncodings()
            names = ros.msg.sensor_msgs.internal.ImageEncoding.AllEncodings;
            encodings = cellfun( ...
                @(enc)ros.msg.sensor_msgs.internal.ImageEncoding.info(enc), ...
                names, 'UniformOutput', false);
            idx = cellfun(@(enc) enc.HasAlpha, encodings);
            out = cellfun(@(enc) enc.Name, encodings(idx), ...
                          'UniformOutput', false);
        end

        function encInfo = info(encoding)
            switch lower(encoding)
              case 'rgb8'
                encInfo = struct( ...
                    'Name','rgb8', ...
                    'DataType', 'uint8', ...
                    'NumChannels', 3, ...
                    'ChannelOrder', [1, 2, 3], ...
                    'HasAlpha', false, ...
                    'IsBayer', false, ...
                    'SensorAlignment', '');
              case 'rgba8'
                encInfo = struct( ...
                    'Name','rgba8', ...
                    'DataType', 'uint8', ...
                    'NumChannels', 4, ...
                    'ChannelOrder', [1, 2, 3, 4], ...
                    'HasAlpha', true, ...
                    'IsBayer', false, ...
                    'SensorAlignment', '');
              case 'rgb16'
                encInfo = struct( ...
                    'Name','rgb16', ...
                    'DataType', 'uint16', ...
                    'NumChannels', 3, ...
                    'ChannelOrder', [1, 2, 3], ...
                    'HasAlpha', false, ...
                    'IsBayer', false, ...
                    'SensorAlignment', '');
              case 'rgba16'
                encInfo = struct( ...
                    'Name','rgba16', ...
                    'DataType', 'uint16', ...
                    'NumChannels', 4, ...
                    'ChannelOrder', [1, 2, 3, 4], ...
                    'HasAlpha', true, ...
                    'IsBayer', false, ...
                    'SensorAlignment', '');
              case 'bgr8'
                encInfo = struct( ...
                    'Name','bgr8', ...
                    'DataType', 'uint8', ...
                    'NumChannels', 3, ...
                    'ChannelOrder', [3, 2, 1], ...
                    'HasAlpha', false, ...
                    'IsBayer', false, ...
                    'SensorAlignment', '');
              case 'bgra8'
                encInfo = struct( ...
                    'Name','bgra8', ...
                    'DataType', 'uint8', ...
                    'NumChannels', 4, ...
                    'ChannelOrder', [3, 2, 1, 4], ...
                    'HasAlpha', true, ...
                    'IsBayer', false, ...
                    'SensorAlignment', '');
              case 'bgr16'
                encInfo = struct( ...
                    'Name','bgr16', ...
                    'DataType', 'uint16', ...
                    'NumChannels', 3, ...
                    'ChannelOrder', [3, 2, 1], ...
                    'HasAlpha', false, ...
                    'IsBayer', false, ...
                    'SensorAlignment', '');
              case 'bgra16'
                encInfo = struct( ...
                    'Name','bgra16', ...
                    'DataType', 'uint16', ...
                    'NumChannels', 4, ...
                    'ChannelOrder', [3, 2, 1, 4], ...
                    'HasAlpha', true, ...
                    'IsBayer', false, ...
                    'SensorAlignment', '');
              case 'mono8'
                encInfo = struct( ...
                    'Name','mono8', ...
                    'DataType', 'uint8', ...
                    'NumChannels', 1, ...
                    'ChannelOrder', 1, ...
                    'HasAlpha', false, ...
                    'IsBayer', false, ...
                    'SensorAlignment', '');
              case 'mono16'
                encInfo = struct( ...
                    'Name','mono16', ...
                    'DataType', 'uint16', ...
                    'NumChannels', 1, ...
                    'ChannelOrder', 1, ...
                    'HasAlpha', false, ...
                    'IsBayer', false, ...
                    'SensorAlignment', '');
              case '32fc1'
                encInfo = struct( ...
                    'Name','32fc1', ...
                    'DataType', 'single', ...
                    'NumChannels', 1, ...
                    'ChannelOrder', 1, ...
                    'HasAlpha', false, ...
                    'IsBayer', false, ...
                    'SensorAlignment', '');
              case '32fc2'
                encInfo = struct( ...
                    'Name','32fc2', ...
                    'DataType', 'single', ...
                    'NumChannels', 2, ...
                    'ChannelOrder', [1, 2], ...
                    'HasAlpha', false, ...
                    'IsBayer', false, ...
                    'SensorAlignment', '');
              case '32fc3'
                encInfo = struct( ...
                    'Name','32fc3', ...
                    'DataType', 'single', ...
                    'NumChannels', 3, ...
                    'ChannelOrder', [1, 2, 3], ...
                    'HasAlpha', false, ...
                    'IsBayer', false, ...
                    'SensorAlignment', '');
              case '32fc4'
                encInfo = struct( ...
                    'Name','32fc4', ...
                    'DataType', 'single', ...
                    'NumChannels', 4, ...
                    'ChannelOrder', [1, 2, 3, 4], ...
                    'HasAlpha', false, ...
                    'IsBayer', false, ...
                    'SensorAlignment', '');
              case '64fc1'
                encInfo = struct( ...
                    'Name','64fc1', ...
                    'DataType', 'double', ...
                    'NumChannels', 1, ...
                    'ChannelOrder', 1, ...
                    'HasAlpha', false, ...
                    'IsBayer', false, ...
                    'SensorAlignment', '');
              case '64fc2'
                encInfo = struct( ...
                    'Name','64fc2', ...
                    'DataType', 'double', ...
                    'NumChannels', 2, ...
                    'ChannelOrder', [1, 2], ...
                    'HasAlpha', false, ...
                    'IsBayer', false, ...
                    'SensorAlignment', '');
              case '64fc3'
                encInfo = struct( ...
                    'Name','64fc3', ...
                    'DataType', 'double', ...
                    'NumChannels', 3, ...
                    'ChannelOrder', [1, 2, 3], ...
                    'HasAlpha', false, ...
                    'IsBayer', false, ...
                    'SensorAlignment', '');
              case '64fc4'
                encInfo = struct( ...
                    'Name','64fc4', ...
                    'DataType', 'double', ...
                    'NumChannels', 4, ...
                    'ChannelOrder', [1, 2, 3, 4], ...
                    'HasAlpha', false, ...
                    'IsBayer', false, ...
                    'SensorAlignment', '');
              case '8uc1'
                encInfo = struct( ...
                    'Name','8uc1', ...
                    'DataType', 'uint8', ...
                    'NumChannels', 1, ...
                    'ChannelOrder', 1, ...
                    'HasAlpha', false, ...
                    'IsBayer', false, ...
                    'SensorAlignment', '');
              case '8uc2'
                encInfo = struct( ...
                    'Name','8uc2', ...
                    'DataType', 'uint8', ...
                    'NumChannels', 2, ...
                    'ChannelOrder', [1, 2], ...
                    'HasAlpha', false, ...
                    'IsBayer', false, ...
                    'SensorAlignment', '');
              case '8uc3'
                encInfo = struct( ...
                    'Name','8uc3', ...
                    'DataType', 'uint8', ...
                    'NumChannels', 3, ...
                    'ChannelOrder', [1, 2, 3], ...
                    'HasAlpha', false, ...
                    'IsBayer', false, ...
                    'SensorAlignment', '');
              case '8uc4'
                encInfo = struct( ...
                    'Name','8uc4', ...
                    'DataType', 'uint8', ...
                    'NumChannels', 4, ...
                    'ChannelOrder', [1, 2, 3, 4], ...
                    'HasAlpha', false, ...
                    'IsBayer', false, ...
                    'SensorAlignment', '');
              case '8sc1'
                encInfo = struct( ...
                    'Name','8sc1', ...
                    'DataType', 'int8', ...
                    'NumChannels', 1, ...
                    'ChannelOrder', 1, ...
                    'HasAlpha', false, ...
                    'IsBayer', false, ...
                    'SensorAlignment', '');
              case '8sc2'
                encInfo = struct( ...
                    'Name','8sc2', ...
                    'DataType', 'int8', ...
                    'NumChannels', 2, ...
                    'ChannelOrder', [1, 2], ...
                    'HasAlpha', false, ...
                    'IsBayer', false, ...
                    'SensorAlignment', '');
              case '8sc3'
                encInfo = struct( ...
                    'Name','8sc3', ...
                    'DataType', 'int8', ...
                    'NumChannels', 3, ...
                    'ChannelOrder', [1, 2, 3], ...
                    'HasAlpha', false, ...
                    'IsBayer', false, ...
                    'SensorAlignment', '');
              case '8sc4'
                encInfo = struct( ...
                    'Name','8sc4', ...
                    'DataType', 'int8', ...
                    'NumChannels', 4, ...
                    'ChannelOrder', [1, 2, 3, 4], ...
                    'HasAlpha', false, ...
                    'IsBayer', false, ...
                    'SensorAlignment', '');
              case '16uc1'
                encInfo = struct( ...
                    'Name','16uc1', ...
                    'DataType', 'uint16', ...
                    'NumChannels', 1, ...
                    'ChannelOrder', 1, ...
                    'HasAlpha', false, ...
                    'IsBayer', false, ...
                    'SensorAlignment', '');
              case '16uc2'
                encInfo = struct( ...
                    'Name','16uc2', ...
                    'DataType', 'uint16', ...
                    'NumChannels', 2, ...
                    'ChannelOrder', [1, 2], ...
                    'HasAlpha', false, ...
                    'IsBayer', false, ...
                    'SensorAlignment', '');
              case '16uc3'
                encInfo = struct( ...
                    'Name','16uc3', ...
                    'DataType', 'uint16', ...
                    'NumChannels', 3, ...
                    'ChannelOrder', [1, 2, 3], ...
                    'HasAlpha', false, ...
                    'IsBayer', false, ...
                    'SensorAlignment', '');
              case '16uc4'
                encInfo = struct( ...
                    'Name','16uc4', ...
                    'DataType', 'uint16', ...
                    'NumChannels', 4, ...
                    'ChannelOrder', [1, 2, 3, 4], ...
                    'HasAlpha', false, ...
                    'IsBayer', false, ...
                    'SensorAlignment', '');
              case '16sc1'
                encInfo = struct( ...
                    'Name','16sc1', ...
                    'DataType', 'int16', ...
                    'NumChannels', 1, ...
                    'ChannelOrder', 1, ...
                    'HasAlpha', false, ...
                    'IsBayer', false, ...
                    'SensorAlignment', '');
              case '16sc2'
                encInfo = struct( ...
                    'Name','16sc2', ...
                    'DataType', 'int16', ...
                    'NumChannels', 2, ...
                    'ChannelOrder', [1, 2], ...
                    'HasAlpha', false, ...
                    'IsBayer', false, ...
                    'SensorAlignment', '');
              case '16sc3'
                encInfo = struct( ...
                    'Name','16sc3', ...
                    'DataType', 'int16', ...
                    'NumChannels', 3, ...
                    'ChannelOrder', [1, 2, 3], ...
                    'HasAlpha', false, ...
                    'IsBayer', false, ...
                    'SensorAlignment', '');
              case '16sc4'
                encInfo = struct( ...
                    'Name','16sc4', ...
                    'DataType', 'int16', ...
                    'NumChannels', 4, ...
                    'ChannelOrder', [1, 2, 3, 4], ...
                    'HasAlpha', false, ...
                    'IsBayer', false, ...
                    'SensorAlignment', '');
              case '32sc1'
                encInfo = struct( ...
                    'Name','32sc1', ...
                    'DataType', 'int32', ...
                    'NumChannels', 1, ...
                    'ChannelOrder', 1, ...
                    'HasAlpha', false, ...
                    'IsBayer', false, ...
                    'SensorAlignment', '');
              case '32sc2'
                encInfo = struct( ...
                    'Name','32sc2', ...
                    'DataType', 'int32', ...
                    'NumChannels', 2, ...
                    'ChannelOrder', [1, 2], ...
                    'HasAlpha', false, ...
                    'IsBayer', false, ...
                    'SensorAlignment', '');
              case '32sc3'
                encInfo = struct( ...
                    'Name','32sc3', ...
                    'DataType', 'int32', ...
                    'NumChannels', 3, ...
                    'ChannelOrder', [1, 2, 3], ...
                    'HasAlpha', false, ...
                    'IsBayer', false, ...
                    'SensorAlignment', '');
              case '32sc4'
                encInfo = struct( ...
                    'Name','32sc4', ...
                    'DataType', 'int32', ...
                    'NumChannels', 4, ...
                    'ChannelOrder', [1, 2, 3, 4], ...
                    'HasAlpha', false, ...
                    'IsBayer', false, ...
                    'SensorAlignment', '');
              case 'bayer_rggb8'
                encInfo = struct( ...
                    'Name','bayer_rggb8', ...
                    'DataType', 'uint8', ...
                    'NumChannels', 1, ...
                    'ChannelOrder', 1, ...
                    'HasAlpha', false, ...
                    'IsBayer', true, ...
                    'SensorAlignment', 'rggb');
              case 'bayer_bggr8'
                encInfo = struct( ...
                    'Name','bayer_bggr8', ...
                    'DataType', 'uint8', ...
                    'NumChannels', 1, ...
                    'ChannelOrder', 1, ...
                    'HasAlpha', false, ...
                    'IsBayer', true, ...
                    'SensorAlignment', 'bggr');
              case 'bayer_gbrg8'
                encInfo = struct( ...
                    'Name','bayer_gbrg8', ...
                    'DataType', 'uint8', ...
                    'NumChannels', 1, ...
                    'ChannelOrder', 1, ...
                    'HasAlpha', false, ...
                    'IsBayer', true, ...
                    'SensorAlignment', 'gbrg');
              case 'bayer_grbg8'
                encInfo = struct( ...
                    'Name','bayer_grbg8', ...
                    'DataType', 'uint8', ...
                    'NumChannels', 1, ...
                    'ChannelOrder', 1, ...
                    'HasAlpha', false, ...
                    'IsBayer', true, ...
                    'SensorAlignment', 'grbg');
              case 'bayer_rggb16'
                encInfo = struct( ...
                    'Name','bayer_rggb16', ...
                    'DataType', 'uint16', ...
                    'NumChannels', 1, ...
                    'ChannelOrder', 1, ...
                    'HasAlpha', false, ...
                    'IsBayer', true, ...
                    'SensorAlignment', 'rggb');
              case 'bayer_bggr16'
                encInfo = struct( ...
                    'Name','bayer_bggr16', ...
                    'DataType', 'uint16', ...
                    'NumChannels', 1, ...
                    'ChannelOrder', 1, ...
                    'HasAlpha', false, ...
                    'IsBayer', true, ...
                    'SensorAlignment', 'bggr');
              case 'bayer_gbrg16'
                encInfo = struct( ...
                    'Name','bayer_gbrg16', ...
                    'DataType', 'uint16', ...
                    'NumChannels', 1, ...
                    'ChannelOrder', 1, ...
                    'HasAlpha', false, ...
                    'IsBayer', true, ...
                    'SensorAlignment', 'gbrg');
              case 'bayer_grbg16'
                encInfo = struct( ...
                    'Name','bayer_grbg16', ...
                    'DataType', 'uint16', ...
                    'NumChannels', 1, ...
                    'ChannelOrder', 1, ...
                    'HasAlpha', false, ...
                    'IsBayer', true, ...
                    'SensorAlignment', 'grbg');
              otherwise
                coder.internal.error('ros:mlroscpp:image:InvalidEncoding');
            end
        end
    end
end
