function cleanPath = setupRosEnv()
%This function is for internal use only. It may be removed in the future.

%   Copyright 2021 The MathWorks, Inc.

    % setup env-variables needed for ROS

    envPathMap = ...
                containers.Map({'win64', 'glnxa64', 'maci64'}, ...
                                   {'PATH', ...            % win64
                                    'LD_LIBRARY_PATH', ...  % glnxa64
                                    'DYLD_LIBRARY_PATH'});  % maci64
    ros1LibPath = containers.Map({'win64','maci64','glnxa64'}, ...
                                     { ...
                                         fullfile(matlabroot,'sys', 'ros1',computer('arch'),'ros1','bin'), ...
                                         fullfile(matlabroot,'sys', 'ros1',computer('arch'),'ros1','lib'),...
                                         fullfile(matlabroot,'sys', 'ros1',computer('arch'),'ros1','lib'),...
           });

    rosConsoleLibPath = containers.Map({'win64','maci64','glnxa64'}, ...
                                     { ...
                                         fullfile(matlabroot,'sys', 'ros1',computer('arch'),'ros1','console_bridge','bin'), ...
                                         fullfile(matlabroot,'sys', 'ros1',computer('arch'),'ros1','console_bridge','lib'),...
                                         fullfile(matlabroot,'sys', 'ros1',computer('arch'),'ros1','console_bridge','lib'),...
           });
    rostinyXML2LibPath = containers.Map({'win64','maci64','glnxa64'}, ...
                                     { ...
                                         fullfile(matlabroot,'sys', 'ros1',computer('arch'),'ros1','tinyxml2','bin'), ...
                                         fullfile(matlabroot,'sys', 'ros1',computer('arch'),'ros1','tinyxml2','lib'),...
                                         fullfile(matlabroot,'sys', 'ros1',computer('arch'),'ros1','tinyxml2','lib'),...
           });
    dataArrayLibPath = fullfile(matlabroot,'extern','bin',computer('arch'));

    rosLZ4LibPath = containers.Map({'win64','maci64','glnxa64'}, ...
                                     { ...
                                         fullfile(matlabroot,'sys', 'ros1',computer('arch'),'ros1','lz4','bin'), ...
                                         fullfile(matlabroot,'sys', 'ros1',computer('arch'),'ros1','lz4','lib'),...
                                         fullfile(matlabroot,'sys', 'ros1',computer('arch'),'ros1','lz4','lib'),...
           });
    
    pathCurrentValue = getenv(envPathMap(computer('arch')));
    setenv(envPathMap(computer('arch')), ...
        strcat(rosLZ4LibPath(computer('arch')),pathsep,dataArrayLibPath,pathsep,ros1LibPath(computer('arch')), pathsep,rosConsoleLibPath(computer('arch')),pathsep, ...
            rostinyXML2LibPath(computer('arch')),pathsep,pathCurrentValue));
    cleanPath = onCleanup(...
        @() setenv(envPathMap(computer('arch')), pathCurrentValue));
end

