# Put a program in the queue. If the program is already in the queue, this does nothing
uint64 token
uint64 program_id
---
# return the position in the queue. might be useful, might not.
uint64 queue_position
