function invalidMessageTypes = getMessageTypesWithCppKeyword
%getMessageTypesWithCppKeyword returns message types which has
%   C++ keyword.

%   Copyright 2020 The MathWorks, Inc.

invalidMessageTypes = {'app_manager/StartAppRequest', 'app_manager/StartAppResponse', 'app_manager/StartApp', 'multimaster_msgs_fkie/Capability', ...
    'multimaster_msgs_fkie/ListDescriptionRequest', 'multimaster_msgs_fkie/ListDescriptionResponse', 'multimaster_msgs_fkie/ListDescription', ...
    'rocon_interaction_msgs/ErrorCodes', 'rocon_interaction_msgs/GetInteractionRequest', 'rocon_interaction_msgs/GetInteractionResponse', ...
    'rocon_interaction_msgs/GetInteraction', 'rocon_interaction_msgs/GetInteractionsRequest', 'rocon_interaction_msgs/GetInteractionsResponse', ...
    'rocon_interaction_msgs/GetInteractions', 'rocon_interaction_msgs/Interaction', ...
    'rocon_interaction_msgs/InteractiveClient', 'rocon_interaction_msgs/InteractiveClients', ...
    'rocon_interaction_msgs/RemoconStatus', 'rocon_interaction_msgs/RequestInteractionRequest', 'rocon_interaction_msgs/RequestInteractionResponse', ...
    'rocon_interaction_msgs/RequestInteraction', 'rocon_interaction_msgs/Roles', 'rocon_interaction_msgs/SetInteractionsRequest', ...
    'rocon_interaction_msgs/SetInteractionsResponse', 'rocon_interaction_msgs/SetInteractions', 'rocon_interaction_msgs/Strings', ...
    'rosapi/GetParamRequest', 'rosapi/GetParamResponse', 'rosapi/GetParam', 'rosbridge_library/TestArrayRequestRequest', ...
    'rosbridge_library/TestArrayRequestResponse', 'rosbridge_library/TestArrayRequest', 'rosbridge_library/TestMultipleRequestFieldsRequest', ...
    'rosbridge_library/TestMultipleRequestFieldsResponse', 'rosbridge_library/TestMultipleRequestFields', 'rosbridge_library/TestMultipleResponseFieldsRequest', ...
    'rosbridge_library/TestMultipleResponseFieldsResponse', 'rosbridge_library/TestMultipleResponseFields'};
    
end