function msg = sensor_msgs_LaserScanStruct
% Message struct definition for sensor_msgs/LaserScan
coder.inline("never")
msg = struct(...
    'MessageType','sensor_msgs/LaserScan',...
    'header',std_msgs_HeaderStruct,...
    'angle_min',ros.internal.ros2.messages.ros2.default_type('single',1,0),...
    'angle_max',ros.internal.ros2.messages.ros2.default_type('single',1,0),...
    'angle_increment',ros.internal.ros2.messages.ros2.default_type('single',1,0),...
    'time_increment',ros.internal.ros2.messages.ros2.default_type('single',1,0),...
    'scan_time',ros.internal.ros2.messages.ros2.default_type('single',1,0),...
    'range_min',ros.internal.ros2.messages.ros2.default_type('single',1,0),...
    'range_max',ros.internal.ros2.messages.ros2.default_type('single',1,0),...
    'ranges',ros.internal.ros2.messages.ros2.default_type('single',NaN,1),...
    'intensities',ros.internal.ros2.messages.ros2.default_type('single',NaN,1));
coder.cstructname(msg,'sensor_msgs_LaserScanStruct_T');
coder.varsize('msg.ranges',[1000000000 1],[1 0]);
coder.varsize('msg.intensities',[1000000000 1],[1 0]);
if ~isempty(coder.target)
    coder.ceval('//',coder.rref(msg));
end
end
