
classdef ExploreFeedback < ros.Message
    %ExploreFeedback MATLAB implementation of nav2d_navigator/ExploreFeedback
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'nav2d_navigator/ExploreFeedback' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'e64a606b3357bbb098996ab9c2799a9f' % The MD5 Checksum of the message definition
        PropertyList = { 'RobotPose' 'TargetPose' 'Distance' } % List of non-constant message properties
        ROSPropertyList = { 'robot_pose' 'target_pose' 'distance' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.geometry_msgs.Pose2D' ...
            'ros.msggen.geometry_msgs.Pose2D' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        RobotPose
        TargetPose
        Distance
    end
    methods
        function set.RobotPose(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Pose2D'};
            validateattributes(val, validClasses, validAttributes, 'ExploreFeedback', 'RobotPose')
            obj.RobotPose = val;
        end
        function set.TargetPose(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Pose2D'};
            validateattributes(val, validClasses, validAttributes, 'ExploreFeedback', 'TargetPose')
            obj.TargetPose = val;
        end
        function set.Distance(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ExploreFeedback', 'Distance');
            obj.Distance = single(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.nav2d_navigator.ExploreFeedback.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.nav2d_navigator.ExploreFeedback(strObj);
        end
    end
end
