classdef GetMessageList
%GetMessageTopicList Get the list of topic and its message type

%   Copyright 2019-2020 The MathWorks, Inc.

    properties
        MsgList = {'gazebo_msgs/Pose',...
                   'gazebo_msgs/Image',...
                   'gazebo_msgs/IMU',...
                   'gazebo_msgs/LaserScan',...
                   'gazebo_msgs/JointState',...
                   'gazebo_msgs/LinkState'}
    end

end
