// Generated by gencpp from file fkie_multimaster_msgs/SyncMasterInfo.msg
// DO NOT EDIT!


#ifndef FKIE_MULTIMASTER_MSGS_MESSAGE_SYNCMASTERINFO_H
#define FKIE_MULTIMASTER_MSGS_MESSAGE_SYNCMASTERINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <fkie_multimaster_msgs/SyncTopicInfo.h>
#include <fkie_multimaster_msgs/SyncTopicInfo.h>
#include <fkie_multimaster_msgs/SyncServiceInfo.h>

namespace fkie_multimaster_msgs
{
template <class ContainerAllocator>
struct SyncMasterInfo_
{
  typedef SyncMasterInfo_<ContainerAllocator> Type;

  SyncMasterInfo_()
    : masteruri()
    , nodes()
    , publisher()
    , subscriber()
    , services()  {
    }
  SyncMasterInfo_(const ContainerAllocator& _alloc)
    : masteruri(_alloc)
    , nodes(_alloc)
    , publisher(_alloc)
    , subscriber(_alloc)
    , services(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _masteruri_type;
  _masteruri_type masteruri;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _nodes_type;
  _nodes_type nodes;

   typedef std::vector< ::fkie_multimaster_msgs::SyncTopicInfo_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::fkie_multimaster_msgs::SyncTopicInfo_<ContainerAllocator> >::other >  _publisher_type;
  _publisher_type publisher;

   typedef std::vector< ::fkie_multimaster_msgs::SyncTopicInfo_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::fkie_multimaster_msgs::SyncTopicInfo_<ContainerAllocator> >::other >  _subscriber_type;
  _subscriber_type subscriber;

   typedef std::vector< ::fkie_multimaster_msgs::SyncServiceInfo_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::fkie_multimaster_msgs::SyncServiceInfo_<ContainerAllocator> >::other >  _services_type;
  _services_type services;





  typedef boost::shared_ptr< ::fkie_multimaster_msgs::SyncMasterInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fkie_multimaster_msgs::SyncMasterInfo_<ContainerAllocator> const> ConstPtr;

}; // struct SyncMasterInfo_

typedef ::fkie_multimaster_msgs::SyncMasterInfo_<std::allocator<void> > SyncMasterInfo;

typedef boost::shared_ptr< ::fkie_multimaster_msgs::SyncMasterInfo > SyncMasterInfoPtr;
typedef boost::shared_ptr< ::fkie_multimaster_msgs::SyncMasterInfo const> SyncMasterInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fkie_multimaster_msgs::SyncMasterInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fkie_multimaster_msgs::SyncMasterInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fkie_multimaster_msgs::SyncMasterInfo_<ContainerAllocator1> & lhs, const ::fkie_multimaster_msgs::SyncMasterInfo_<ContainerAllocator2> & rhs)
{
  return lhs.masteruri == rhs.masteruri &&
    lhs.nodes == rhs.nodes &&
    lhs.publisher == rhs.publisher &&
    lhs.subscriber == rhs.subscriber &&
    lhs.services == rhs.services;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fkie_multimaster_msgs::SyncMasterInfo_<ContainerAllocator1> & lhs, const ::fkie_multimaster_msgs::SyncMasterInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fkie_multimaster_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fkie_multimaster_msgs::SyncMasterInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fkie_multimaster_msgs::SyncMasterInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fkie_multimaster_msgs::SyncMasterInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fkie_multimaster_msgs::SyncMasterInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fkie_multimaster_msgs::SyncMasterInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fkie_multimaster_msgs::SyncMasterInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fkie_multimaster_msgs::SyncMasterInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ba4b02792114bcc4bae507c60dd14d66";
  }

  static const char* value(const ::fkie_multimaster_msgs::SyncMasterInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xba4b02792114bcc4ULL;
  static const uint64_t static_value2 = 0xbae507c60dd14d66ULL;
};

template<class ContainerAllocator>
struct DataType< ::fkie_multimaster_msgs::SyncMasterInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fkie_multimaster_msgs/SyncMasterInfo";
  }

  static const char* value(const ::fkie_multimaster_msgs::SyncMasterInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fkie_multimaster_msgs::SyncMasterInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string masteruri\n"
"string[] nodes\n"
"fkie_multimaster_msgs/SyncTopicInfo[] publisher\n"
"fkie_multimaster_msgs/SyncTopicInfo[] subscriber\n"
"fkie_multimaster_msgs/SyncServiceInfo[] services\n"
"================================================================================\n"
"MSG: fkie_multimaster_msgs/SyncTopicInfo\n"
"string topic\n"
"string node\n"
"string nodeuri\n"
"================================================================================\n"
"MSG: fkie_multimaster_msgs/SyncServiceInfo\n"
"string service\n"
"string serviceuri\n"
"string node\n"
"string nodeuri\n"
;
  }

  static const char* value(const ::fkie_multimaster_msgs::SyncMasterInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fkie_multimaster_msgs::SyncMasterInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.masteruri);
      stream.next(m.nodes);
      stream.next(m.publisher);
      stream.next(m.subscriber);
      stream.next(m.services);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SyncMasterInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fkie_multimaster_msgs::SyncMasterInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fkie_multimaster_msgs::SyncMasterInfo_<ContainerAllocator>& v)
  {
    s << indent << "masteruri: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.masteruri);
    s << indent << "nodes[]" << std::endl;
    for (size_t i = 0; i < v.nodes.size(); ++i)
    {
      s << indent << "  nodes[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.nodes[i]);
    }
    s << indent << "publisher[]" << std::endl;
    for (size_t i = 0; i < v.publisher.size(); ++i)
    {
      s << indent << "  publisher[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::fkie_multimaster_msgs::SyncTopicInfo_<ContainerAllocator> >::stream(s, indent + "    ", v.publisher[i]);
    }
    s << indent << "subscriber[]" << std::endl;
    for (size_t i = 0; i < v.subscriber.size(); ++i)
    {
      s << indent << "  subscriber[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::fkie_multimaster_msgs::SyncTopicInfo_<ContainerAllocator> >::stream(s, indent + "    ", v.subscriber[i]);
    }
    s << indent << "services[]" << std::endl;
    for (size_t i = 0; i < v.services.size(); ++i)
    {
      s << indent << "  services[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::fkie_multimaster_msgs::SyncServiceInfo_<ContainerAllocator> >::stream(s, indent + "    ", v.services[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FKIE_MULTIMASTER_MSGS_MESSAGE_SYNCMASTERINFO_H
