
classdef GetGroupStateRequest < ros.Message
    %GetGroupStateRequest MATLAB implementation of adhoc_communication/GetGroupStateRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'adhoc_communication/GetGroupStateRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '967d0b0c0d858ded8a6a69abbce0c981' % The MD5 Checksum of the message definition
        PropertyList = { 'GroupName' } % List of non-constant message properties
        ROSPropertyList = { 'group_name' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        GroupName
    end
    methods
        function set.GroupName(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'GetGroupStateRequest', 'GroupName');
            obj.GroupName = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.adhoc_communication.GetGroupStateRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.adhoc_communication.GetGroupStateRequest(strObj);
        end
    end
end
