
classdef SendExpClusterRequest < ros.Message
    %SendExpClusterRequest MATLAB implementation of adhoc_communication/SendExpClusterRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'adhoc_communication/SendExpClusterRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'd1172e2fa3a1e03e6528ece001803f85' % The MD5 Checksum of the message definition
        PropertyList = { 'Cluster' 'Topic' 'DstRobot' } % List of non-constant message properties
        ROSPropertyList = { 'cluster' 'topic' 'dst_robot' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.adhoc_communication.ExpCluster' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Cluster
        Topic
        DstRobot
    end
    methods
        function set.Cluster(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.adhoc_communication.ExpCluster'};
            validateattributes(val, validClasses, validAttributes, 'SendExpClusterRequest', 'Cluster')
            obj.Cluster = val;
        end
        function set.Topic(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'SendExpClusterRequest', 'Topic');
            obj.Topic = char(val);
        end
        function set.DstRobot(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'SendExpClusterRequest', 'DstRobot');
            obj.DstRobot = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.adhoc_communication.SendExpClusterRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.adhoc_communication.SendExpClusterRequest(strObj);
        end
    end
end
