function [libDirs, libMap] = getLibInfo
%This function is for internal use only. It may be removed in the future.

%GETLIBINFO gets the info of libDirs, libDirsMap and libMap

%   Copyright 2020 The MathWorks, Inc.

libDirsMap = containers.Map({'win64','maci64','glnxa64'}, ...
    { ...
    fullfile(matlabroot,'extern','lib','win64','microsoft') ...
    fullfile(matlabroot,'extern','bin','maci64'),...
    fullfile(matlabroot,'extern','bin','glnxa64'),...
    });
libDirs = libDirsMap(computer('arch'));
libMap = containers.Map({'win64','maci64','glnxa64'}, ...
    { ...
    'libMatlabDataArray', ...
    fullfile(libDirs,'libMatlabDataArray.dylib'),...
    fullfile(libDirs,'libMatlabDataArray.so'),...
    });
end