// Generated by gencpp from file applanix_msgs/Version.msg
// DO NOT EDIT!


#ifndef APPLANIX_MSGS_MESSAGE_VERSION_H
#define APPLANIX_MSGS_MESSAGE_VERSION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <applanix_msgs/TimeDistance.h>

namespace applanix_msgs
{
template <class ContainerAllocator>
struct Version_
{
  typedef Version_<ContainerAllocator> Type;

  Version_()
    : td()
    , system_version()
    , primary_gnss_version()
    , secondary_gnss_version()
    , total_hours(0.0)
    , num_runs(0)
    , avg_run_length(0.0)
    , longest_run(0.0)
    , current_run(0.0)  {
      system_version.assign(0);

      primary_gnss_version.assign(0);

      secondary_gnss_version.assign(0);
  }
  Version_(const ContainerAllocator& _alloc)
    : td(_alloc)
    , system_version()
    , primary_gnss_version()
    , secondary_gnss_version()
    , total_hours(0.0)
    , num_runs(0)
    , avg_run_length(0.0)
    , longest_run(0.0)
    , current_run(0.0)  {
  (void)_alloc;
      system_version.assign(0);

      primary_gnss_version.assign(0);

      secondary_gnss_version.assign(0);
  }



   typedef  ::applanix_msgs::TimeDistance_<ContainerAllocator>  _td_type;
  _td_type td;

   typedef boost::array<uint8_t, 120>  _system_version_type;
  _system_version_type system_version;

   typedef boost::array<uint8_t, 80>  _primary_gnss_version_type;
  _primary_gnss_version_type primary_gnss_version;

   typedef boost::array<uint8_t, 80>  _secondary_gnss_version_type;
  _secondary_gnss_version_type secondary_gnss_version;

   typedef float _total_hours_type;
  _total_hours_type total_hours;

   typedef uint32_t _num_runs_type;
  _num_runs_type num_runs;

   typedef float _avg_run_length_type;
  _avg_run_length_type avg_run_length;

   typedef float _longest_run_type;
  _longest_run_type longest_run;

   typedef float _current_run_type;
  _current_run_type current_run;





  typedef boost::shared_ptr< ::applanix_msgs::Version_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::applanix_msgs::Version_<ContainerAllocator> const> ConstPtr;

}; // struct Version_

typedef ::applanix_msgs::Version_<std::allocator<void> > Version;

typedef boost::shared_ptr< ::applanix_msgs::Version > VersionPtr;
typedef boost::shared_ptr< ::applanix_msgs::Version const> VersionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::applanix_msgs::Version_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::applanix_msgs::Version_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace applanix_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/mathworks/home/pmurali/Documents/Working/matlab_msg_gen_ros1/glnxa64/src/geometry_msgs/msg'], 'std_msgs': ['/mathworks/devel/sbs/31/pmurali.Brobot.j1329247.2/matlab/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg'], 'applanix_msgs': ['/mathworks/home/pmurali/Documents/Working/matlab_msg_gen_ros1/glnxa64/src/applanix_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::applanix_msgs::Version_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::applanix_msgs::Version_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::applanix_msgs::Version_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::applanix_msgs::Version_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::applanix_msgs::Version_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::applanix_msgs::Version_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::applanix_msgs::Version_<ContainerAllocator> >
{
  static const char* value()
  {
    return "436db5a21d31ed873f1f24270392aeca";
  }

  static const char* value(const ::applanix_msgs::Version_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x436db5a21d31ed87ULL;
  static const uint64_t static_value2 = 0x3f1f24270392aecaULL;
};

template<class ContainerAllocator>
struct DataType< ::applanix_msgs::Version_<ContainerAllocator> >
{
  static const char* value()
  {
    return "applanix_msgs/Version";
  }

  static const char* value(const ::applanix_msgs::Version_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::applanix_msgs::Version_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Group 99\n"
"TimeDistance td\n"
"\n"
"uint8[120] system_version\n"
"uint8[80] primary_gnss_version\n"
"uint8[80] secondary_gnss_version\n"
"\n"
"float32 total_hours\n"
"uint32 num_runs\n"
"float32 avg_run_length\n"
"float32 longest_run\n"
"float32 current_run\n"
"\n"
"================================================================================\n"
"MSG: applanix_msgs/TimeDistance\n"
"float64 time1\n"
"float64 time2\n"
"float64 distance\n"
"uint8 time_types\n"
"uint8 distance_type\n"
;
  }

  static const char* value(const ::applanix_msgs::Version_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::applanix_msgs::Version_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.td);
      stream.next(m.system_version);
      stream.next(m.primary_gnss_version);
      stream.next(m.secondary_gnss_version);
      stream.next(m.total_hours);
      stream.next(m.num_runs);
      stream.next(m.avg_run_length);
      stream.next(m.longest_run);
      stream.next(m.current_run);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Version_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::applanix_msgs::Version_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::applanix_msgs::Version_<ContainerAllocator>& v)
  {
    s << indent << "td: ";
    s << std::endl;
    Printer< ::applanix_msgs::TimeDistance_<ContainerAllocator> >::stream(s, indent + "  ", v.td);
    s << indent << "system_version[]" << std::endl;
    for (size_t i = 0; i < v.system_version.size(); ++i)
    {
      s << indent << "  system_version[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.system_version[i]);
    }
    s << indent << "primary_gnss_version[]" << std::endl;
    for (size_t i = 0; i < v.primary_gnss_version.size(); ++i)
    {
      s << indent << "  primary_gnss_version[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.primary_gnss_version[i]);
    }
    s << indent << "secondary_gnss_version[]" << std::endl;
    for (size_t i = 0; i < v.secondary_gnss_version.size(); ++i)
    {
      s << indent << "  secondary_gnss_version[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.secondary_gnss_version[i]);
    }
    s << indent << "total_hours: ";
    Printer<float>::stream(s, indent + "  ", v.total_hours);
    s << indent << "num_runs: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.num_runs);
    s << indent << "avg_run_length: ";
    Printer<float>::stream(s, indent + "  ", v.avg_run_length);
    s << indent << "longest_run: ";
    Printer<float>::stream(s, indent + "  ", v.longest_run);
    s << indent << "current_run: ";
    Printer<float>::stream(s, indent + "  ", v.current_run);
  }
};

} // namespace message_operations
} // namespace ros

#endif // APPLANIX_MSGS_MESSAGE_VERSION_H
