
classdef Alarms < ros.Message
    %Alarms MATLAB implementation of robotnik_msgs/Alarms
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'robotnik_msgs/Alarms' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '83113d787282f31e7cff7eb72a2096c0' % The MD5 Checksum of the message definition
        PropertyList = { 'Alarms_' } % List of non-constant message properties
        ROSPropertyList = { 'alarms' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.robotnik_msgs.AlarmSensor' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Alarms_
    end
    methods
        function set.Alarms_(obj, val)
            if isempty(val)
                % Allow empty [] input
                val = ros.msggen.robotnik_msgs.AlarmSensor.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validClasses = {'ros.msggen.robotnik_msgs.AlarmSensor'};
            validateattributes(val, validClasses, validAttributes, 'Alarms', 'Alarms_')
            obj.Alarms_ = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.robotnik_msgs.Alarms.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.robotnik_msgs.Alarms(strObj);
        end
    end
end
