# Msg 33
uint16 transaction

uint8 TRIGGER_POSITIVE_EDGE=0
uint8 TRIGGER_NEGATIVE_EDGE=1
uint8 event_1_trigger
uint8 event_2_trigger
uint8 event_3_trigger
uint8 event_4_trigger
uint8 event_5_trigger
uint8 event_6_trigger

uint16 event_1_guard_time
uint16 event_2_guard_time
uint16 event_3_guard_time
uint16 event_4_guard_time
uint16 event_5_guard_time
uint16 event_6_guard_time

uint8 POLARITY_POSITIVE_PULSE=0
uint8 POLARITY_NEGATIVE_PULSE=1
uint8 POLARITY_PASS_THROUGH=2
uint8 pps_out_polarity
