// Generated by gencpp from file rocon_std_msgs/EmptyStringRequest.msg
// DO NOT EDIT!


#ifndef ROCON_STD_MSGS_MESSAGE_EMPTYSTRINGREQUEST_H
#define ROCON_STD_MSGS_MESSAGE_EMPTYSTRINGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rocon_std_msgs
{
template <class ContainerAllocator>
struct EmptyStringRequest_
{
  typedef EmptyStringRequest_<ContainerAllocator> Type;

  EmptyStringRequest_()
    {
    }
  EmptyStringRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::rocon_std_msgs::EmptyStringRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rocon_std_msgs::EmptyStringRequest_<ContainerAllocator> const> ConstPtr;

}; // struct EmptyStringRequest_

typedef ::rocon_std_msgs::EmptyStringRequest_<std::allocator<void> > EmptyStringRequest;

typedef boost::shared_ptr< ::rocon_std_msgs::EmptyStringRequest > EmptyStringRequestPtr;
typedef boost::shared_ptr< ::rocon_std_msgs::EmptyStringRequest const> EmptyStringRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rocon_std_msgs::EmptyStringRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rocon_std_msgs::EmptyStringRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace rocon_std_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rocon_std_msgs::EmptyStringRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rocon_std_msgs::EmptyStringRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rocon_std_msgs::EmptyStringRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rocon_std_msgs::EmptyStringRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rocon_std_msgs::EmptyStringRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rocon_std_msgs::EmptyStringRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rocon_std_msgs::EmptyStringRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::rocon_std_msgs::EmptyStringRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::rocon_std_msgs::EmptyStringRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rocon_std_msgs/EmptyStringRequest";
  }

  static const char* value(const ::rocon_std_msgs::EmptyStringRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rocon_std_msgs::EmptyStringRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::rocon_std_msgs::EmptyStringRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rocon_std_msgs::EmptyStringRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EmptyStringRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rocon_std_msgs::EmptyStringRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::rocon_std_msgs::EmptyStringRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROCON_STD_MSGS_MESSAGE_EMPTYSTRINGREQUEST_H
