
classdef MotionPlanRequest < ros.Message
    %MotionPlanRequest MATLAB implementation of moveit_msgs/MotionPlanRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'moveit_msgs/MotionPlanRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '9544d5f3b9cf69a0e1e7f8c75d87f54b' % The MD5 Checksum of the message definition
        PropertyList = { 'WorkspaceParameters' 'StartState' 'GoalConstraints' 'PathConstraints' 'TrajectoryConstraints' 'ReferenceTrajectories' 'PipelineId' 'PlannerId' 'GroupName' 'NumPlanningAttempts' 'AllowedPlanningTime' 'MaxVelocityScalingFactor' 'MaxAccelerationScalingFactor' 'CartesianSpeedEndEffectorLink' 'MaxCartesianSpeed' } % List of non-constant message properties
        ROSPropertyList = { 'workspace_parameters' 'start_state' 'goal_constraints' 'path_constraints' 'trajectory_constraints' 'reference_trajectories' 'pipeline_id' 'planner_id' 'group_name' 'num_planning_attempts' 'allowed_planning_time' 'max_velocity_scaling_factor' 'max_acceleration_scaling_factor' 'cartesian_speed_end_effector_link' 'max_cartesian_speed' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.moveit_msgs.WorkspaceParameters' ...
            'ros.msggen.moveit_msgs.RobotState' ...
            'ros.msggen.moveit_msgs.Constraints' ...
            'ros.msggen.moveit_msgs.Constraints' ...
            'ros.msggen.moveit_msgs.TrajectoryConstraints' ...
            'ros.msggen.moveit_msgs.GenericTrajectory' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        WorkspaceParameters
        StartState
        GoalConstraints
        PathConstraints
        TrajectoryConstraints
        ReferenceTrajectories
        PipelineId
        PlannerId
        GroupName
        NumPlanningAttempts
        AllowedPlanningTime
        MaxVelocityScalingFactor
        MaxAccelerationScalingFactor
        CartesianSpeedEndEffectorLink
        MaxCartesianSpeed
    end
    methods
        function set.WorkspaceParameters(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.moveit_msgs.WorkspaceParameters'};
            validateattributes(val, validClasses, validAttributes, 'MotionPlanRequest', 'WorkspaceParameters')
            obj.WorkspaceParameters = val;
        end
        function set.StartState(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.moveit_msgs.RobotState'};
            validateattributes(val, validClasses, validAttributes, 'MotionPlanRequest', 'StartState')
            obj.StartState = val;
        end
        function set.GoalConstraints(obj, val)
            if isempty(val)
                % Allow empty [] input
                val = ros.msggen.moveit_msgs.Constraints.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validClasses = {'ros.msggen.moveit_msgs.Constraints'};
            validateattributes(val, validClasses, validAttributes, 'MotionPlanRequest', 'GoalConstraints')
            obj.GoalConstraints = val;
        end
        function set.PathConstraints(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.moveit_msgs.Constraints'};
            validateattributes(val, validClasses, validAttributes, 'MotionPlanRequest', 'PathConstraints')
            obj.PathConstraints = val;
        end
        function set.TrajectoryConstraints(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.moveit_msgs.TrajectoryConstraints'};
            validateattributes(val, validClasses, validAttributes, 'MotionPlanRequest', 'TrajectoryConstraints')
            obj.TrajectoryConstraints = val;
        end
        function set.ReferenceTrajectories(obj, val)
            if isempty(val)
                % Allow empty [] input
                val = ros.msggen.moveit_msgs.GenericTrajectory.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validClasses = {'ros.msggen.moveit_msgs.GenericTrajectory'};
            validateattributes(val, validClasses, validAttributes, 'MotionPlanRequest', 'ReferenceTrajectories')
            obj.ReferenceTrajectories = val;
        end
        function set.PipelineId(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'MotionPlanRequest', 'PipelineId');
            obj.PipelineId = char(val);
        end
        function set.PlannerId(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'MotionPlanRequest', 'PlannerId');
            obj.PlannerId = char(val);
        end
        function set.GroupName(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'MotionPlanRequest', 'GroupName');
            obj.GroupName = char(val);
        end
        function set.NumPlanningAttempts(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'MotionPlanRequest', 'NumPlanningAttempts');
            obj.NumPlanningAttempts = int32(val);
        end
        function set.AllowedPlanningTime(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'MotionPlanRequest', 'AllowedPlanningTime');
            obj.AllowedPlanningTime = double(val);
        end
        function set.MaxVelocityScalingFactor(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'MotionPlanRequest', 'MaxVelocityScalingFactor');
            obj.MaxVelocityScalingFactor = double(val);
        end
        function set.MaxAccelerationScalingFactor(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'MotionPlanRequest', 'MaxAccelerationScalingFactor');
            obj.MaxAccelerationScalingFactor = double(val);
        end
        function set.CartesianSpeedEndEffectorLink(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'MotionPlanRequest', 'CartesianSpeedEndEffectorLink');
            obj.CartesianSpeedEndEffectorLink = char(val);
        end
        function set.MaxCartesianSpeed(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'MotionPlanRequest', 'MaxCartesianSpeed');
            obj.MaxCartesianSpeed = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.moveit_msgs.MotionPlanRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.moveit_msgs.MotionPlanRequest(strObj);
        end
    end
end
