classdef Constants < ros.slros.internal.cgen.Constants
%This class is for internal use only. It may be removed in the future.

%cgen.Constants - Constants used for generating C++ ROS code

%   Copyright 2014-2021 The MathWorks, Inc.

%#codegen

    properties(Constant)

        NodeInterface = struct(...
            'HeaderFile', 'ros2nodeinterface.h', ...
            'SourceFile', 'ros2nodeinterface.cpp', ...
            'MainFile', 'main.cpp', ...
            'PubSubCommonHeader', 'pubsub_common.h', ...
            'HeaderTemplate', fullfile(fileparts(mfilename('fullpath')),'interface.h.tmpl'), ...
            'SourceFileTemplate', fullfile(fileparts(mfilename('fullpath')),'interface.cpp.tmpl'), ...
            'PubSubCommonTemplate', fullfile(fileparts(mfilename('fullpath')),'ros2_blocks_common.h.tmpl'), ...
            'MainTemplate', fullfile(fileparts(mfilename('fullpath')),'main.cpp.tmpl'), ...
            'NonresuableFcnHeaderTemplate', fullfile(fileparts(mfilename('fullpath')),'interface_nonreusablefcn.h.tmpl'), ...
            'NonresuableFcnSourceFileTemplate', fullfile(fileparts(mfilename('fullpath')),'interface_nonreusablefcn.cpp.tmpl') ...
                              )
        ROS2ModelInfoFile = ros.ros2.ProjectTool.getROS2ModelInfoFile;
        ROS2PredefinedCode = struct(...
            'ConversionUtilsHeaderFile', 'slros_msgconvert_utils.h', ...
            'Location',   fullfile(toolboxdir('ros'), 'slros2', 'src') ...
                                   )
    end

end
