// Generated by gencpp from file cob_object_detection_msgs/BagTrainObject.msg
// DO NOT EDIT!


#ifndef COB_OBJECT_DETECTION_MSGS_MESSAGE_BAGTRAINOBJECT_H
#define COB_OBJECT_DETECTION_MSGS_MESSAGE_BAGTRAINOBJECT_H

#include <ros/service_traits.h>


#include <cob_object_detection_msgs/BagTrainObjectRequest.h>
#include <cob_object_detection_msgs/BagTrainObjectResponse.h>


namespace cob_object_detection_msgs
{

struct BagTrainObject
{

typedef BagTrainObjectRequest Request;
typedef BagTrainObjectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BagTrainObject
} // namespace cob_object_detection_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cob_object_detection_msgs::BagTrainObject > {
  static const char* value()
  {
    return "e054914e8be752a53cf516ce4c1d583c";
  }

  static const char* value(const ::cob_object_detection_msgs::BagTrainObject&) { return value(); }
};

template<>
struct DataType< ::cob_object_detection_msgs::BagTrainObject > {
  static const char* value()
  {
    return "cob_object_detection_msgs/BagTrainObject";
  }

  static const char* value(const ::cob_object_detection_msgs::BagTrainObject&) { return value(); }
};


// service_traits::MD5Sum< ::cob_object_detection_msgs::BagTrainObjectRequest> should match 
// service_traits::MD5Sum< ::cob_object_detection_msgs::BagTrainObject > 
template<>
struct MD5Sum< ::cob_object_detection_msgs::BagTrainObjectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cob_object_detection_msgs::BagTrainObject >::value();
  }
  static const char* value(const ::cob_object_detection_msgs::BagTrainObjectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cob_object_detection_msgs::BagTrainObjectRequest> should match 
// service_traits::DataType< ::cob_object_detection_msgs::BagTrainObject > 
template<>
struct DataType< ::cob_object_detection_msgs::BagTrainObjectRequest>
{
  static const char* value()
  {
    return DataType< ::cob_object_detection_msgs::BagTrainObject >::value();
  }
  static const char* value(const ::cob_object_detection_msgs::BagTrainObjectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cob_object_detection_msgs::BagTrainObjectResponse> should match 
// service_traits::MD5Sum< ::cob_object_detection_msgs::BagTrainObject > 
template<>
struct MD5Sum< ::cob_object_detection_msgs::BagTrainObjectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cob_object_detection_msgs::BagTrainObject >::value();
  }
  static const char* value(const ::cob_object_detection_msgs::BagTrainObjectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cob_object_detection_msgs::BagTrainObjectResponse> should match 
// service_traits::DataType< ::cob_object_detection_msgs::BagTrainObject > 
template<>
struct DataType< ::cob_object_detection_msgs::BagTrainObjectResponse>
{
  static const char* value()
  {
    return DataType< ::cob_object_detection_msgs::BagTrainObject >::value();
  }
  static const char* value(const ::cob_object_detection_msgs::BagTrainObjectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COB_OBJECT_DETECTION_MSGS_MESSAGE_BAGTRAINOBJECT_H
