
classdef ParseTableSceneRequest < ros.Message
    %ParseTableSceneRequest MATLAB implementation of r2_msgs/ParseTableSceneRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'r2_msgs/ParseTableSceneRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'fab6d5f499de320aad10749bce1f85cf' % The MD5 Checksum of the message definition
        PropertyList = { 'Cmd' } % List of non-constant message properties
        ROSPropertyList = { 'cmd' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Cmd
    end
    methods
        function set.Cmd(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ParseTableSceneRequest', 'Cmd');
            obj.Cmd = logical(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.r2_msgs.ParseTableSceneRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.r2_msgs.ParseTableSceneRequest(strObj);
        end
    end
end
