// Generated by gencpp from file sr_ronex_msgs/SPI.msg
// DO NOT EDIT!


#ifndef SR_RONEX_MSGS_MESSAGE_SPI_H
#define SR_RONEX_MSGS_MESSAGE_SPI_H

#include <ros/service_traits.h>


#include <sr_ronex_msgs/SPIRequest.h>
#include <sr_ronex_msgs/SPIResponse.h>


namespace sr_ronex_msgs
{

struct SPI
{

typedef SPIRequest Request;
typedef SPIResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SPI
} // namespace sr_ronex_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sr_ronex_msgs::SPI > {
  static const char* value()
  {
    return "bc18af37b05e0138c71d03e14c29082d";
  }

  static const char* value(const ::sr_ronex_msgs::SPI&) { return value(); }
};

template<>
struct DataType< ::sr_ronex_msgs::SPI > {
  static const char* value()
  {
    return "sr_ronex_msgs/SPI";
  }

  static const char* value(const ::sr_ronex_msgs::SPI&) { return value(); }
};


// service_traits::MD5Sum< ::sr_ronex_msgs::SPIRequest> should match 
// service_traits::MD5Sum< ::sr_ronex_msgs::SPI > 
template<>
struct MD5Sum< ::sr_ronex_msgs::SPIRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sr_ronex_msgs::SPI >::value();
  }
  static const char* value(const ::sr_ronex_msgs::SPIRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sr_ronex_msgs::SPIRequest> should match 
// service_traits::DataType< ::sr_ronex_msgs::SPI > 
template<>
struct DataType< ::sr_ronex_msgs::SPIRequest>
{
  static const char* value()
  {
    return DataType< ::sr_ronex_msgs::SPI >::value();
  }
  static const char* value(const ::sr_ronex_msgs::SPIRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sr_ronex_msgs::SPIResponse> should match 
// service_traits::MD5Sum< ::sr_ronex_msgs::SPI > 
template<>
struct MD5Sum< ::sr_ronex_msgs::SPIResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sr_ronex_msgs::SPI >::value();
  }
  static const char* value(const ::sr_ronex_msgs::SPIResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sr_ronex_msgs::SPIResponse> should match 
// service_traits::DataType< ::sr_ronex_msgs::SPI > 
template<>
struct DataType< ::sr_ronex_msgs::SPIResponse>
{
  static const char* value()
  {
    return DataType< ::sr_ronex_msgs::SPI >::value();
  }
  static const char* value(const ::sr_ronex_msgs::SPIResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SR_RONEX_MSGS_MESSAGE_SPI_H
