
classdef GNSSControl < ros.Message
    %GNSSControl MATLAB implementation of applanix_msgs/GNSSControl
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'applanix_msgs/GNSSControl' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '1afc77ae104c2a173006233b6540798b' % The MD5 Checksum of the message definition
        PropertyList = { 'Transaction' 'Control' } % List of non-constant message properties
        ROSPropertyList = { 'transaction' 'control' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
        CONTROLPRIMARYGNSSCONFIG = uint8(0)
        CONTROLPRIMARYGNSSRESET = uint8(1)
        CONTROLSECONDARYGNSSCONFIG = uint8(2)
        CONTROLSECONDARYGNSSRESET = uint8(3)
    end
    properties
        Transaction
        Control
    end
    methods
        function set.Transaction(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'GNSSControl', 'Transaction');
            obj.Transaction = uint16(val);
        end
        function set.Control(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'GNSSControl', 'Control');
            obj.Control = uint8(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.applanix_msgs.GNSSControl.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.applanix_msgs.GNSSControl(strObj);
        end
    end
end
