
classdef MouseEvent < ros.Message
    %MouseEvent MATLAB implementation of image_view2/MouseEvent
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.

    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'image_view2/MouseEvent' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '7ffa73624c1be385169a9e6e23460224' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'Type' 'Key' 'X' 'Y' 'Width' 'Height' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'type' 'key' 'x' 'y' 'width' 'height' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
        KEYPRESSED = int32(1)
        MOUSELEFTUP = int32(2)
        MOUSELEFTDOWN = int32(3)
        MOUSEMOVE = int32(4)
        MOUSERIGHTDOWN = int32(5)
    end
    properties
        Header
        Type
        Key
        X
        Y
        Width
        Height
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'MouseEvent', 'Header')
            obj.Header = val;
        end
        function set.Type(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'MouseEvent', 'Type');
            obj.Type = int32(val);
        end
        function set.Key(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'MouseEvent', 'Key');
            obj.Key = int32(val);
        end
        function set.X(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'MouseEvent', 'X');
            obj.X = int32(val);
        end
        function set.Y(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'MouseEvent', 'Y');
            obj.Y = int32(val);
        end
        function set.Width(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'MouseEvent', 'Width');
            obj.Width = int32(val);
        end
        function set.Height(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'MouseEvent', 'Height');
            obj.Height = int32(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.image_view2.MouseEvent.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.image_view2.MouseEvent(strObj);
        end
    end
end
